// src/domains/journey-booking/application/commands/create-journey-booking-snapshot.command.ts

// -----------------------------------------------------------------------------
// Journey Booking Snapshot — Create Command
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Domain Value Objects
// -----------------------------------------------------------------------------

import type {
  JourneyBookingPublicId,
  JourneyBookingOriginName,
  JourneyBookingDestinationName,
  JourneyBookingCoordinates,
  JourneyBookingDepartureAt,
  JourneyBookingArrivalAt,
  JourneyBookingTimezone,
} from '../../domain/value-objects';

// -----------------------------------------------------------------------------
// Command
// -----------------------------------------------------------------------------

/**
 * Creates the historical Journey Booking Snapshot.
 *
 * The snapshot belongs to an existing Journey Booking aggregate and preserves
 * the journey and vehicle information captured at booking time.
 *
 * The snapshot public ID is generated by the domain entity factory.
 */
export class CreateJourneyBookingSnapshotCommand extends Command {
  constructor(
    // -------------------------------------------------------------------------
    // Journey Booking
    // -------------------------------------------------------------------------

    /**
     * Public identifier of the Journey Booking receiving this snapshot.
     */
    public readonly journeyBookingPublicId: JourneyBookingPublicId,

    // -------------------------------------------------------------------------
    // Journey Snapshot
    // -------------------------------------------------------------------------

    /**
     * Origin name captured at booking time.
     */
    public readonly originName: JourneyBookingOriginName,

    /**
     * Destination name captured at booking time.
     */
    public readonly destinationName: JourneyBookingDestinationName,

    /**
     * Origin geographic coordinates captured at booking time.
     */
    public readonly originCoordinates: JourneyBookingCoordinates,

    /**
     * Destination geographic coordinates captured at booking time.
     */
    public readonly destinationCoordinates: JourneyBookingCoordinates,

    /**
     * Scheduled departure captured at booking time.
     */
    public readonly departureAt: JourneyBookingDepartureAt,

    /**
     * IANA timezone captured at booking time.
     */
    public readonly timezone: JourneyBookingTimezone,

    // -------------------------------------------------------------------------
    // Correlation
    // -------------------------------------------------------------------------

    /**
     * Correlation identifier for distributed tracing and workflow tracking.
     */
    public readonly correlationId: string,

    // -------------------------------------------------------------------------
    // Optional Snapshot Information
    // -------------------------------------------------------------------------

    /**
     * Scheduled arrival captured at booking time.
     */
    public readonly arrivalAt?: JourneyBookingArrivalAt,

    /**
     * Vehicle make captured at booking time.
     */
    public readonly vehicleMake?: string,

    /**
     * Vehicle model captured at booking time.
     */
    public readonly vehicleModel?: string,

    /**
     * Vehicle manufacturing year captured at booking time.
     */
    public readonly vehicleYear?: number,

    /**
     * Vehicle color captured at booking time.
     */
    public readonly vehicleColor?: string,

    /**
     * Vehicle registration captured at booking time.
     */
    public readonly vehicleRegistration?: string,

    // -------------------------------------------------------------------------
    // Causation
    // -------------------------------------------------------------------------

    /**
     * Optional identifier of the command or event that caused this command.
     */
    public readonly causationId?: string,
  ) {
    super();
  }
}