// -----------------------------------------------------------------------------
// Journey Booking — Authorize Payment Request DTO
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS / Swagger
// -----------------------------------------------------------------------------

import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Validation
// -----------------------------------------------------------------------------

import {
  IsDateString,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';

// -----------------------------------------------------------------------------
// DTO
// -----------------------------------------------------------------------------

/**
 * Request payload for authorizing payment for a Journey Booking.
 *
 * This DTO represents the REST request body only.
 *
 * The Journey Booking public ID is supplied through the route parameter.
 * The correlation ID is generated by the controller when the request enters
 * the application boundary.
 *
 * The transaction public ID is supplied by the client because it was
 * established during the payment-creation step and is required to identify
 * the payment transaction being authorized.
 *
 * Primitive request values are converted into domain value objects by the
 * presentation/application mapping layer before the
 * AuthorizeJourneyBookingPaymentCommand is created.
 */
export class AuthorizeJourneyBookingPaymentDto {
  // ===========================================================================
  // Financial Transaction
  // ===========================================================================

  @ApiProperty({
    description:
      'Public identifier of the transaction associated with the Journey Booking payment.',
    example: 'TXN-8K3P2Q1A',
  })
  @IsString()
  @MinLength(1)
  @MaxLength(100)
  transactionPublicId!: string;

  // ===========================================================================
  // Causation
  // ===========================================================================

  @ApiPropertyOptional({
    description:
      'Identifier of the command or event that caused this payment authorization request, when applicable.',
    example: 'cmd-01J8XYZDEF',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MinLength(1)
  @MaxLength(200)
  causationId?: string;

  // ===========================================================================
  // Authorization Time
  // ===========================================================================

  @ApiPropertyOptional({
    description:
      'Explicit payment authorization timestamp. When omitted, the aggregate uses the current time.',
    example: '2026-08-18T17:00:00.000Z',
    format: 'date-time',
    required: false,
  })
  @IsOptional()
  @IsDateString()
  authorizedAt?: string;
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default AuthorizeJourneyBookingPaymentDto;
