// -----------------------------------------------------------------------------
// Accounting Journal — Create Accounting Journal Request DTO
// -----------------------------------------------------------------------------
//
// REST request DTO for creating an Accounting Journal aggregate.
//
// Aggregate:
//
// AccountingJournalAggregate
// └── AccountingJournalEntity
//
// User-facing intent:
//
//     Create Accounting Journal
//
// This request exposes only information that may reasonably be required from
// the caller.
//
// Required:
//
// - none, when the application defaults the currency to KES and the journal
//   does not need to belong to an Accounting Period at creation time.
//
// Optional:
//
// - currency;
// - periodPublicId.
//
// The Accounting Journal identity is generated by the domain.
//
// The internal Accounting Period identity is never exposed through the REST
// boundary. If a period is supplied, the application layer resolves:
//
//     periodPublicId
//          ↓
//     AccountingPeriodRepository
//          ↓
//     internal period identity
//
// This request does NOT supply:
//
// - journal public ID;
// - journal internal ID;
// - period internal ID;
// - journal status;
// - createdAt;
// - updatedAt;
// - correlationId;
// - causationId.
//
// Those values belong to the domain, persistence, or application execution
// context.
//
// This DTO does NOT:
//
// - create AccountingJournalEntity;
// - create AccountingJournalAggregate;
// - load the Accounting Period;
// - validate Accounting Period existence;
// - validate Accounting Period state;
// - persist the aggregate;
// - access Prisma;
// - perform authorization.
//
// -----------------------------------------------------------------------------
//
// Example — create journal without explicitly selecting a period:
//
//     {}
//
// Example — create journal for a specific period:
//
//     {
//       "periodPublicId": "7b4c7b7e-2d2a-4e6c-8a8b-7f2d9a1c1234"
//     }
//
// Example — explicitly specify currency:
//
//     {
//       "currency": "KES",
//       "periodPublicId": "7b4c7b7e-2d2a-4e6c-8a8b-7f2d9a1c1234"
//     }
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS Swagger
// -----------------------------------------------------------------------------

import { ApiPropertyOptional } from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Class Transformer
// -----------------------------------------------------------------------------

import { Transform, type TransformFnParams } from 'class-transformer';

// -----------------------------------------------------------------------------
// Class Validator
// -----------------------------------------------------------------------------

import {
  IsIn,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

export const ACCOUNTING_JOURNAL_DEFAULT_CURRENCY = 'KES';

export const ACCOUNTING_JOURNAL_CURRENCIES = [
  'KES',
  'USD',
  'EUR',
  'GBP',
] as const;

export const ACCOUNTING_JOURNAL_CURRENCY_LENGTH = 3;

// =============================================================================
// DTO
// =============================================================================

/**
 * REST request for creating an Accounting Journal.
 *
 * The Accounting Journal identity and lifecycle state are generated by the
 * domain.
 *
 * Currency defaults to KES when omitted.
 *
 * An Accounting Period is optional because the journal may be created before
 * it is associated with a period.
 */
export class CreateAccountingJournalRequestDto {
  // ===========================================================================
  // Currency
  // ===========================================================================

  /**
   * Accounting currency of the journal.
   *
   * When omitted, the application should use KES.
   *
   * The value is normalized to uppercase before application-layer mapping.
   */
  @ApiPropertyOptional({
    example: 'KES',
    enum: ACCOUNTING_JOURNAL_CURRENCIES,
    default: ACCOUNTING_JOURNAL_DEFAULT_CURRENCY,
    description:
      'Accounting currency of the journal. Defaults to KES when omitted.',
  })
  @IsOptional()
  @Transform(({ value }: TransformFnParams): unknown =>
    typeof value === 'string' ? value.trim().toUpperCase() : value,
  )
  @IsString({
    message: 'currency must be a string.',
  })
  @MinLength(ACCOUNTING_JOURNAL_CURRENCY_LENGTH, {
    message: `currency must be exactly ${ACCOUNTING_JOURNAL_CURRENCY_LENGTH} characters.`,
  })
  @MaxLength(ACCOUNTING_JOURNAL_CURRENCY_LENGTH, {
    message: `currency must be exactly ${ACCOUNTING_JOURNAL_CURRENCY_LENGTH} characters.`,
  })
  @IsIn(ACCOUNTING_JOURNAL_CURRENCIES, {
    message: 'currency must be one of KES, USD, EUR, or GBP.',
  })
  currency?: string;

  // ===========================================================================
  // Accounting Period
  // ===========================================================================

  /**
   * Public identity of the Accounting Period to associate with the journal.
   *
   * The application layer resolves this public identity to the internal
   * Accounting Period identity before constructing the command.
   */
  @ApiPropertyOptional({
    example: '7b4c7b7e-2d2a-4e6c-8a8b-7f2d9a1c1234',
    description:
      'Optional public identity of the Accounting Period associated with the journal.',
    format: 'uuid',
  })
  @IsOptional()
  @IsString({
    message: 'periodPublicId must be a string.',
  })
  @IsUUID('4', {
    message: 'periodPublicId must be a valid UUID.',
  })
  periodPublicId?: string;
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default CreateAccountingJournalRequestDto;
