import { ApiProperty } from '@nestjs/swagger';
import {
  IsBoolean,
  IsEnum,
  IsNumber,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';

import { JourneyWaypointType } from '../../../domain/value-objects/journey-waypoint-type.vo';

// -----------------------------------------------------------------------------
// DTO
// -----------------------------------------------------------------------------

/**
 * Request body for adding a waypoint to a Journey.
 *
 * The Journey public ID is supplied by the route:
 *
 *     POST /journeys/:journeyPublicId/waypoints
 *
 * The waypoint public ID is generated by the application layer because the
 * waypoint is created as part of the Journey aggregate.
 *
 * Correlation and causation identifiers are also application concerns and
 * should not be supplied as domain configuration by the HTTP client.
 */
export class AddWaypointDto {
  @ApiProperty({
    enum: JourneyWaypointType,
    example: JourneyWaypointType.WAYPOINT,
    description: 'Type of Journey waypoint.',
  })
  @IsEnum(JourneyWaypointType)
  type!: JourneyWaypointType;

  @ApiProperty({
    example: 1,
    description: 'Sequence number of the waypoint within the Journey corridor.',
  })
  @IsNumber()
  sequence!: number;

  @ApiProperty({
    example: 'Naivasha',
    description: 'Waypoint location name.',
  })
  @IsString()
  @MinLength(1)
  @MaxLength(200)
  name!: string;

  @ApiProperty({
    example: -0.7172,
    description: 'Waypoint latitude.',
  })
  @IsNumber()
  latitude!: number;

  @ApiProperty({
    example: 36.431,
    description: 'Waypoint longitude.',
  })
  @IsNumber()
  longitude!: number;

  @ApiProperty({
    example: true,
    description: 'Whether passenger pickup is allowed at this waypoint.',
  })
  @IsBoolean()
  pickupAllowed!: boolean;

  @ApiProperty({
    example: true,
    description: 'Whether passenger dropoff is allowed at this waypoint.',
  })
  @IsBoolean()
  dropoffAllowed!: boolean;
}
