import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
} from 'class-validator';

// -----------------------------------------------------------------------------
// sisiMove — Cancel Journey DTO
// -----------------------------------------------------------------------------
//
// HTTP request body for cancelling a Journey.
//
// The following values are intentionally NOT part of this DTO:
// - journeyPublicId → supplied by the route parameter
// - correlationId   → generated by the controller
// - causationId     → application-layer concern
//
// The controller/application layer constructs the CancelJourneyCommand from
// the validated HTTP input.
//
// -----------------------------------------------------------------------------

export class CancelJourneyDto {
  // ---------------------------------------------------------------------------
  // Cancellation Reason
  // ---------------------------------------------------------------------------

  @ApiProperty({
    example: 'Provider is no longer available for the journey.',
    description: 'Reason for cancelling the Journey.',
    maxLength: 500,
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(500)
  readonly reason!: string;

  // ---------------------------------------------------------------------------
  // Cancellation Timestamp
  // ---------------------------------------------------------------------------

  @ApiPropertyOptional({
    example: '2026-08-15T09:30:00.000Z',
    description:
      'Optional effective cancellation timestamp. When omitted, the backend uses the current time.',
    format: 'date-time',
  })
  @IsOptional()
  @IsDateString()
  readonly cancelledAt?: string;
}
