// -----------------------------------------------------------------------------
// Path: src/domains/journey/presentation/dto/publish-journey.dto.ts
// -----------------------------------------------------------------------------
//
// sisiMove — Publish Journey DTO
//
// HTTP body contract for:
//
//   POST /journeys/:journeyPublicId/publish
//
// The Journey public ID comes from the route parameter.
// The correlation ID is generated by the controller.
// The client may optionally provide publishedAt.
//
// -----------------------------------------------------------------------------

import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsDateString, IsOptional } from 'class-validator';

// -----------------------------------------------------------------------------
// DTO
// -----------------------------------------------------------------------------

export class PublishJourneyDto {
  @ApiPropertyOptional({
    example: '2026-10-02T08:30:00.000Z',
    description:
      'Optional effective publication timestamp. When omitted, the current time is used.',
    format: 'date-time',
  })
  @IsOptional()
  @IsDateString()
  publishedAt?: string;
}