// -----------------------------------------------------------------------------
// Assets — Upload Asset Command
// -----------------------------------------------------------------------------
//
// Application command for uploading a physical Asset and completing the
// creation of the corresponding Asset aggregate.
//
// User-facing intent:
//
//     Upload Asset
//
// This command is the entry point for the complete upload workflow.
//
// The command carries:
//
// - physical file content;
// - Asset metadata required for creation;
// - storage metadata;
// - file metadata;
// - application correlation metadata.
//
// The UploadAssetHandler is the application-level orchestrator.
//
// It is responsible for:
//
// 1. uploading the physical object through AssetStoragePort;
// 2. constructing CreateAssetCommand;
// 3. delegating Asset aggregate creation to CreateAssetHandler;
// 4. transitioning the newly created Asset from UPLOADING to UPLOADED;
// 5. persisting the completed aggregate.
//
// This command does NOT:
//
// - directly access storage providers;
// - directly manipulate Prisma;
// - create AssetEntity;
// - create AssetAggregate;
// - generate AssetPublicId;
// - determine AssetStatus;
// - construct domain events;
// - implement Asset lifecycle rules.
//
// Physical storage belongs to AssetStoragePort.
//
// Asset aggregate creation belongs to CreateAssetHandler.
//
// Asset lifecycle belongs to AssetAggregate / AssetEntity.
//
// Persistence belongs to AssetRepository.
//
// -----------------------------------------------------------------------------
//
// Aggregate boundary:
//
//     AssetAggregate
//     └── AssetEntity
//
// The aggregate does not yet exist when this command begins.
//
// AssetPublicId is therefore intentionally NOT supplied.
//
// The AssetPublicId is generated by AssetEntity.create() as part of the
// delegated CreateAssetCommand workflow.
//
// -----------------------------------------------------------------------------
//
// Storage boundary:
//
// Physical content is represented by a storage-neutral Node.js Readable stream.
//
// The command deliberately does NOT carry:
//
// - Express.Multer.File;
// - Express request objects;
// - AWS SDK objects;
// - Google Cloud SDK objects;
// - Azure SDK objects;
// - Cloudinary SDK objects;
// - filesystem-specific objects.
//
// -----------------------------------------------------------------------------
//
// Correlation / Causation:
//
// - correlationId identifies the end-to-end Upload Asset operation;
// - causationId optionally identifies the command or domain event that caused
//   this operation.
//
// These values are propagated into the delegated CreateAssetCommand and the
// resulting domain events.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Node.js Stream
// -----------------------------------------------------------------------------

import type { Readable } from 'node:stream';

// -----------------------------------------------------------------------------
// Foundation — Application Command
// -----------------------------------------------------------------------------

import type { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Assets — Domain Value Objects
// -----------------------------------------------------------------------------

import type {
  AssetIdentityPublicId,
  AssetType,
  AssetCategory,
  AssetVisibility,
  AssetStorageProvider,
  AssetBucket,
  AssetObjectKey,
  AssetOriginalFilename,
  AssetMimeType,
  AssetSizeBytes,
} from '../../domain/value-objects';

// =============================================================================
// Command
// =============================================================================

/**
 * Command for uploading a physical Asset.
 *
 * The command represents the user-facing intent:
 *
 *     Upload Asset
 *
 * The Asset aggregate does not exist when this command begins.
 *
 * The UploadAssetHandler therefore orchestrates:
 *
 *     physical upload
 *          ↓
 *     Asset creation
 *          ↓
 *     UPLOADING → UPLOADED
 */
export class UploadAssetCommand implements Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    /**
     * Identity that owns the Asset.
     *
     * The reference remains an opaque cross-domain Identity public identifier.
     */
    public readonly ownerIdentityPublicId: AssetIdentityPublicId | undefined,

    /**
     * Asset type.
     */
    public readonly type: AssetType,

    /**
     * Asset category.
     */
    public readonly category: AssetCategory,

    /**
     * Asset visibility.
     */
    public readonly visibility: AssetVisibility,

    /**
     * Storage provider containing the physical object.
     */
    public readonly storageProvider: AssetStorageProvider,

    /**
     * Storage bucket or container.
     */
    public readonly bucket: AssetBucket,

    /**
     * Storage object key.
     */
    public readonly objectKey: AssetObjectKey,

    /**
     * Original client-provided filename, when available.
     */
    public readonly originalFilename: AssetOriginalFilename | undefined,

    /**
     * MIME type of the physical Asset.
     */
    public readonly mimeType: AssetMimeType,

    /**
     * Expected physical Asset size.
     */
    public readonly sizeBytes: AssetSizeBytes,

    /**
     * Physical Asset content.
     *
     * The stream is deliberately framework-independent and provider-independent.
     */
    public readonly content: Readable,

    /**
     * Correlation identifier for the complete Upload Asset operation.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or domain event that caused this
     * operation.
     */
    public readonly causationId?: string,
  ) {}
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default UploadAssetCommand;
