// -----------------------------------------------------------------------------
// Identity — Create Permission Request DTO
// -----------------------------------------------------------------------------
//
// REST request DTO for creating a Permission aggregate.
//
// The DTO represents transport-level intent only.
//
// It does NOT:
//
// - construct PermissionEntity;
// - construct PermissionAggregate;
// - generate PermissionPublicId;
// - persist the Permission;
// - assign the Permission to a Role;
// - create RolePermission relationships;
// - evaluate authorization;
// - access Prisma;
// - emit domain events;
// - communicate with external systems.
//
// The application layer maps this DTO into:
//
//     CreatePermissionCommand
//
// The command then carries domain-ready value objects:
//
//     PermissionCode
//     PermissionResource
//     PermissionAction
//
// The domain remains responsible for final normalization and invariant
// enforcement.
//
// -----------------------------------------------------------------------------
//
// Required inputs:
//
// - name
// - code
// - resource
// - action
// - isSystem
// - isActive
// - correlationId
//
// Optional inputs:
//
// - description
// - causationId
//
// -----------------------------------------------------------------------------
//
// Example:
//
//     {
//       "name": "Create Journey",
//       "code": "JOURNEY_CREATE",
//       "resource": "JOURNEY",
//       "action": "CREATE",
//       "description": "Allows creation of journeys.",
//       "isSystem": true,
//       "isActive": true,
//       "correlationId": "COR-01K3R8Z1M4",
//       "causationId": "CMD-01K3R8Y6M4"
//     }
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS Swagger
// -----------------------------------------------------------------------------

import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Class Transformer
// -----------------------------------------------------------------------------

import { Transform, type TransformFnParams } from 'class-transformer';

// -----------------------------------------------------------------------------
// Class Validator
// -----------------------------------------------------------------------------

import {
  IsBoolean,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';

// =============================================================================
// Helpers
// =============================================================================

const trimString = ({ value }: TransformFnParams): unknown =>
  typeof value === 'string' ? value.trim() : value;

// =============================================================================
// Constants
// =============================================================================

const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 128;

const MIN_CODE_LENGTH = 1;
const MAX_CODE_LENGTH = 128;

const MIN_RESOURCE_LENGTH = 1;
const MAX_RESOURCE_LENGTH = 128;

const MIN_ACTION_LENGTH = 1;
const MAX_ACTION_LENGTH = 128;

const MIN_DESCRIPTION_LENGTH = 1;
const MAX_DESCRIPTION_LENGTH = 512;

const MIN_CORRELATION_ID_LENGTH = 1;
const MAX_CORRELATION_ID_LENGTH = 128;

const MIN_CAUSATION_ID_LENGTH = 1;
const MAX_CAUSATION_ID_LENGTH = 128;

// =============================================================================
// DTO
// =============================================================================

/**
 * REST request for creating a Permission aggregate.
 *
 * This DTO contains transport-level primitives only.
 *
 * Domain value objects are created by the application boundary when mapping
 * this request into CreatePermissionCommand.
 *
 * The Permission public identifier is intentionally omitted because it is
 * generated by the domain/entity creation process.
 */
export class CreatePermissionRequestDto {
  // ===========================================================================
  // Name
  // ===========================================================================

  /**
   * Human-readable name of the Permission.
   */
  @ApiProperty({
    example: 'Create Journey',
    description: 'Human-readable name of the Permission.',
    minLength: MIN_NAME_LENGTH,
    maxLength: MAX_NAME_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'name must be a string.',
  })
  @MinLength(MIN_NAME_LENGTH, {
    message: 'name must not be empty.',
  })
  @MaxLength(MAX_NAME_LENGTH, {
    message: `name must not exceed ${MAX_NAME_LENGTH} characters.`,
  })
  name!: string;

  // ===========================================================================
  // Code
  // ===========================================================================

  /**
   * Stable machine-readable Permission code.
   *
   * The application layer converts this value into PermissionCode.
   */
  @ApiProperty({
    example: 'JOURNEY_CREATE',
    description:
      'Stable machine-readable Permission code used at the authorization boundary.',
    minLength: MIN_CODE_LENGTH,
    maxLength: MAX_CODE_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'code must be a string.',
  })
  @MinLength(MIN_CODE_LENGTH, {
    message: 'code must not be empty.',
  })
  @MaxLength(MAX_CODE_LENGTH, {
    message: `code must not exceed ${MAX_CODE_LENGTH} characters.`,
  })
  code!: string;

  // ===========================================================================
  // Resource
  // ===========================================================================

  /**
   * Resource protected by the Permission.
   *
   * The application layer converts this value into PermissionResource.
   */
  @ApiProperty({
    example: 'JOURNEY',
    description: 'Resource protected by the Permission.',
    minLength: MIN_RESOURCE_LENGTH,
    maxLength: MAX_RESOURCE_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'resource must be a string.',
  })
  @MinLength(MIN_RESOURCE_LENGTH, {
    message: 'resource must not be empty.',
  })
  @MaxLength(MAX_RESOURCE_LENGTH, {
    message: `resource must not exceed ${MAX_RESOURCE_LENGTH} characters.`,
  })
  resource!: string;

  // ===========================================================================
  // Action
  // ===========================================================================

  /**
   * Action authorized by the Permission.
   *
   * The application layer converts this value into PermissionAction.
   */
  @ApiProperty({
    example: 'CREATE',
    description: 'Action authorized by the Permission.',
    minLength: MIN_ACTION_LENGTH,
    maxLength: MAX_ACTION_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'action must be a string.',
  })
  @MinLength(MIN_ACTION_LENGTH, {
    message: 'action must not be empty.',
  })
  @MaxLength(MAX_ACTION_LENGTH, {
    message: `action must not exceed ${MAX_ACTION_LENGTH} characters.`,
  })
  action!: string;

  // ===========================================================================
  // Description
  // ===========================================================================

  /**
   * Optional human-readable description of the Permission.
   */
  @ApiPropertyOptional({
    example: 'Allows creation of journeys.',
    description: 'Optional human-readable description of the Permission.',
    nullable: true,
    minLength: MIN_DESCRIPTION_LENGTH,
    maxLength: MAX_DESCRIPTION_LENGTH,
  })
  @Transform(trimString)
  @IsOptional()
  @IsString({
    message: 'description must be a string.',
  })
  @MinLength(MIN_DESCRIPTION_LENGTH, {
    message: 'description must not be empty when supplied.',
  })
  @MaxLength(MAX_DESCRIPTION_LENGTH, {
    message: `description must not exceed ${MAX_DESCRIPTION_LENGTH} characters.`,
  })
  description?: string;

  // ===========================================================================
  // System Permission
  // ===========================================================================

  /**
   * Indicates whether the Permission is system-managed.
   *
   * Authorization to create system Permissions belongs to the application/
   * security boundary and is not enforced by this DTO.
   */
  @ApiProperty({
    example: true,
    description:
      'Indicates whether the Permission is system-managed. Authorization to create system Permissions is enforced outside the DTO.',
    default: false,
  })
  @IsBoolean({
    message: 'isSystem must be a boolean.',
  })
  isSystem!: boolean;

  // ===========================================================================
  // Active
  // ===========================================================================

  /**
   * Indicates whether the newly created Permission should initially be
   * active.
   */
  @ApiProperty({
    example: true,
    description: 'Indicates whether the Permission should initially be active.',
    default: true,
  })
  @IsBoolean({
    message: 'isActive must be a boolean.',
  })
  isActive!: boolean;

  // ===========================================================================
  // Correlation
  // ===========================================================================

  /**
   * Correlation identifier for the Permission creation operation.
   */
  @ApiProperty({
    example: 'COR-01K3R8Z1M4',
    description:
      'Correlation identifier for the Permission creation operation and resulting domain event.',
    minLength: MIN_CORRELATION_ID_LENGTH,
    maxLength: MAX_CORRELATION_ID_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'correlationId must be a string.',
  })
  @MinLength(MIN_CORRELATION_ID_LENGTH, {
    message: 'correlationId must not be empty.',
  })
  @MaxLength(MAX_CORRELATION_ID_LENGTH, {
    message: `correlationId must not exceed ${MAX_CORRELATION_ID_LENGTH} characters.`,
  })
  correlationId!: string;

  // ===========================================================================
  // Causation
  // ===========================================================================

  /**
   * Optional identifier of the command, event, or operation that caused this
   * Permission creation request.
   */
  @ApiPropertyOptional({
    example: 'CMD-01K3R8Y6M4',
    description:
      'Optional identifier of the command, event, or operation that caused this Permission creation request.',
    nullable: true,
    minLength: MIN_CAUSATION_ID_LENGTH,
    maxLength: MAX_CAUSATION_ID_LENGTH,
  })
  @Transform(trimString)
  @IsOptional()
  @IsString({
    message: 'causationId must be a string.',
  })
  @MinLength(MIN_CAUSATION_ID_LENGTH, {
    message: 'causationId must not be empty when supplied.',
  })
  @MaxLength(MAX_CAUSATION_ID_LENGTH, {
    message: `causationId must not exceed ${MAX_CAUSATION_ID_LENGTH} characters.`,
  })
  causationId?: string;
}

// -----------------------------------------------------------------------------
// Exported Constants
// -----------------------------------------------------------------------------

export {
  MIN_NAME_LENGTH as PERMISSION_CREATE_NAME_MIN_LENGTH,
  MAX_NAME_LENGTH as PERMISSION_CREATE_NAME_MAX_LENGTH,
  MIN_CODE_LENGTH as PERMISSION_CREATE_CODE_MIN_LENGTH,
  MAX_CODE_LENGTH as PERMISSION_CREATE_CODE_MAX_LENGTH,
  MIN_RESOURCE_LENGTH as PERMISSION_CREATE_RESOURCE_MIN_LENGTH,
  MAX_RESOURCE_LENGTH as PERMISSION_CREATE_RESOURCE_MAX_LENGTH,
  MIN_ACTION_LENGTH as PERMISSION_CREATE_ACTION_MIN_LENGTH,
  MAX_ACTION_LENGTH as PERMISSION_CREATE_ACTION_MAX_LENGTH,
  MIN_DESCRIPTION_LENGTH as PERMISSION_CREATE_DESCRIPTION_MIN_LENGTH,
  MAX_DESCRIPTION_LENGTH as PERMISSION_CREATE_DESCRIPTION_MAX_LENGTH,
  MIN_CORRELATION_ID_LENGTH as PERMISSION_CREATE_CORRELATION_ID_MIN_LENGTH,
  MAX_CORRELATION_ID_LENGTH as PERMISSION_CREATE_CORRELATION_ID_MAX_LENGTH,
  MIN_CAUSATION_ID_LENGTH as PERMISSION_CREATE_CAUSATION_ID_MIN_LENGTH,
  MAX_CAUSATION_ID_LENGTH as PERMISSION_CREATE_CAUSATION_ID_MAX_LENGTH,
};
