// -----------------------------------------------------------------------------
// Verification — Revoke Request DTO
// -----------------------------------------------------------------------------
//
// REST request DTO for revoking a Verification aggregate.
//
// Aggregate:
//
// VerificationAggregate
// └── VerificationEntity
//     └── VerificationRequestEntity[]
//
// This DTO represents the transport-level business intent to revoke an
// eligible Verification.
//
// The target Verification is identified by the route:
//
//     PATCH /verifications/:verificationPublicId/revoke
//
// The authenticated Identity performing the operation is resolved from the
// authenticated security context.
//
// The application layer is responsible for supplying:
// - the target Verification;
// - the authenticated reviewer/revoker Identity;
// - correlation metadata;
// - causation metadata;
// - the revocation timestamp.
//
// The aggregate is responsible for:
//
// - validating the revocation reason;
// - validating the current Verification lifecycle state;
// - enforcing revocation rules;
// - transitioning the Verification to REVOKED;
// - recording VerificationRevokedEvent.
//
// This DTO does NOT:
//
// - identify the authenticated reviewer;
// - identify the Verification aggregate;
// - provide correlation metadata;
// - provide causation metadata;
// - provide lifecycle timestamps;
// - mutate VerificationEntity directly;
// - mutate VerificationRequestEntity directly;
// - construct entities;
// - reject or expire VerificationRequests;
// - modify Identity state;
// - modify Identity roles;
// - revoke authentication credentials;
// - terminate sessions;
// - send notifications;
// - perform external side effects.
//
// -----------------------------------------------------------------------------
//
// Expected lifecycle:
//
// VERIFIED ───────► REVOKED
//
// REVOKED is terminal.
//
// The aggregate determines whether the current Verification state is eligible
// for revocation.
//
// -----------------------------------------------------------------------------
//
// Revocation reason:
//
// `reason` describes why the Verification is being revoked.
//
// The aggregate remains responsible for final business validation and
// normalization of the reason.
//
// -----------------------------------------------------------------------------
//
// Security context:
//
// The Identity performing the revocation is NOT supplied by the caller.
//
// It is obtained from:
//
//     req.user.sub
//
// and converted to IdentityPublicId by the HTTP/application boundary.
//
// -----------------------------------------------------------------------------
//
// Example:
//
//     {
//       "reason": "Verification evidence is no longer valid."
//     }
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS Swagger
// -----------------------------------------------------------------------------

import { ApiProperty } from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Class Transformer
// -----------------------------------------------------------------------------

import { Transform, type TransformFnParams } from 'class-transformer';

// -----------------------------------------------------------------------------
// Class Validator
// -----------------------------------------------------------------------------

import { IsString, MaxLength, MinLength } from 'class-validator';

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

const trimString = ({ value }: TransformFnParams): unknown =>
  typeof value === 'string' ? value.trim() : value;

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const MIN_REASON_LENGTH = 1;
const MAX_REASON_LENGTH = 1000;

// -----------------------------------------------------------------------------
// DTO
// -----------------------------------------------------------------------------

/**
 * REST request for revoking a Verification aggregate.
 *
 * Represents the business input required to transition an eligible
 * Verification into the terminal REVOKED lifecycle state.
 *
 * Required transport input:
 *
 * - reason
 *
 * The following values are intentionally NOT supplied by the client:
 *
 * - identityPublicId;
 * - revokedByPublicId;
 * - correlationId;
 * - causationId;
 * - revokedAt;
 * - Verification status;
 * - Verification level;
 * - VerificationRequest state;
 * - VerificationRequest evidence;
 * - domain events;
 * - persistence/internal identifiers.
 *
 * The authenticated actor is resolved from the security context and lifecycle
 * metadata is generated by the application/domain boundaries.
 */
export class RevokeVerificationRequestDto {
  // ===========================================================================
  // Reason
  // ===========================================================================

  /**
   * Business reason for revoking the Verification.
   *
   * The aggregate remains responsible for applying any additional domain
   * normalization or business validation.
   */
  @ApiProperty({
    example: 'Verification evidence is no longer valid.',
    description:
      'Business reason for revoking the Verification. The aggregate performs final domain validation and normalization.',
    minLength: MIN_REASON_LENGTH,
    maxLength: MAX_REASON_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'reason must be a string.',
  })
  @MinLength(MIN_REASON_LENGTH, {
    message: 'reason must not be empty.',
  })
  @MaxLength(MAX_REASON_LENGTH, {
    message: `reason must not exceed ${MAX_REASON_LENGTH} characters.`,
  })
  reason!: string;
}

// -----------------------------------------------------------------------------
// Exported Constants
// -----------------------------------------------------------------------------

export {
  MIN_REASON_LENGTH as VERIFICATION_REVOKE_REASON_MIN_LENGTH,
  MAX_REASON_LENGTH as VERIFICATION_REVOKE_REASON_MAX_LENGTH,
};
