// -----------------------------------------------------------------------------
// Foundation — Security — Refresh Token Hasher
// -----------------------------------------------------------------------------
//
// Application-facing abstraction for hashing and verifying refresh tokens.
//
// Refresh tokens are opaque bearer credentials generated by TokenGenerator.
//
// The abstraction intentionally knows nothing about:
// - Session;
// - Authentication;
// - Identity;
// - persistence;
// - Prisma;
// - HTTP;
// - JWT;
// - the concrete hashing algorithm.
//
// -----------------------------------------------------------------------------

/**
 * Application-facing abstraction for refresh-token cryptographic operations.
 */
export interface RefreshTokenHasher {
  // ---------------------------------------------------------------------------
  // Hash
  // ---------------------------------------------------------------------------

  /**
   * Hashes a raw refresh token.
   *
   * The returned value is the opaque cryptographic representation that may
   * be stored inside SessionRefreshTokenHash.
   */
  hash(token: string): string;

  // ---------------------------------------------------------------------------
  // Compare
  // ---------------------------------------------------------------------------

  /**
   * Verifies a raw refresh token against a previously stored hash.
   *
   * Returns true when the token matches.
   */
  compare(token: string, hash: string): boolean;
}
