// -----------------------------------------------------------------------------
// Authentication — Authenticate Login Command
// -----------------------------------------------------------------------------
//
// Application command for executing the complete user login workflow.
//
// The command represents the application-level intent:
//
//     Authenticate Login
//
// Unlike AuthenticateCommand, which is responsible only for credential
// authentication, AuthenticateLoginCommand represents the complete login
// orchestration:
//
//     credentials
//          │
//          ▼
//     Authentication
//          │
//          │ success
//          ▼
//        Device
//          │
//          ▼
//        Session
//          │
//          ├── refresh token
//          │      │
//          │      ▼
//          │   hashed token
//          │
//          └── access token
//
// The command carries only information supplied by the login request.
// Values belonging to aggregate identity, session identity, and token
// generation are resolved or generated by the application workflow.
//
// The individual aggregates retain ownership of their own state and
// invariants.
//
// -----------------------------------------------------------------------------
//
// Aggregate boundaries:
//
// Identity
// └── IdentityEntity
//
// Authentication
// └── AuthenticationEntity
//
// Device
// └── DeviceEntity
//
// Session
// └── SessionEntity
//
// Each remains an independent aggregate.
//
// The login workflow coordinates these aggregates without merging their
// boundaries.
//
// -----------------------------------------------------------------------------
//
// Responsibilities of the login workflow:
//
// - authenticate the supplied credentials;
// - resolve the authenticated Identity through Authentication;
// - resolve or create the appropriate Device;
// - validate the Device for authentication;
// - record Device activity;
// - generate a refresh token;
// - hash the refresh token;
// - create a new Session;
// - generate an access token;
// - return the resulting login credentials.
//
// Every successful login creates a new refresh-token family.
//
// -----------------------------------------------------------------------------
//
// This command does NOT:
//
// - resolve Identity directly;
// - accept identityPublicId;
// - accept authenticationPublicId;
// - accept devicePublicId;
// - accept sessionPublicId;
// - accept tokenFamilyPublicId;
// - accept a refresh token;
// - accept a refresh token hash;
// - accept an access token;
// - hash passwords;
// - compare passwords;
// - hash refresh tokens;
// - generate tokens;
// - access Prisma;
// - access infrastructure directly;
// - mutate aggregates directly;
// - create domain events directly;
// - persist itself;
// - send notifications.
//
// Those responsibilities belong to the appropriate application, domain,
// repository, security, and infrastructure boundaries.
//
// -----------------------------------------------------------------------------
//
// Credential input:
//
// The command accepts:
//
// - emailOrPhoneNumber;
// - password.
//
// `emailOrPhoneNumber` is the public login identifier.
//
// It may represent either:
//
// - an authoritative email address; or
// - an authoritative phone number.
//
// The credential authentication workflow resolves the corresponding
// Identity and Authentication aggregate.
//
// `password` is transient plaintext credential input.
//
// It MUST NOT be:
//
// - logged;
// - persisted;
// - included in domain events;
// - stored on any aggregate;
// - included in application events or audit payloads.
//
// -----------------------------------------------------------------------------
//
// Device:
//
// A successful login is associated with a Device.
//
// The command therefore carries the information necessary for the application
// workflow to resolve an existing Device or create one.
//
// The command does NOT contain DevicePublicId.
//
// `DeviceFingerprint` identifies the client device within the scope of an
// Identity.
//
// The command does not generate, derive, or interpret the fingerprint.
//
// Device metadata is informational context supplied by the client and is
// passed to Device creation when a matching Device does not already exist.
//
// -----------------------------------------------------------------------------
//
// Session:
//
// A successful login creates a new Session.
//
// Session context is supplied through the appropriate Session value objects:
//
// - SessionIpAddress;
// - SessionUserAgent;
// - SessionCountryCode;
// - SessionCity.
//
// The command does not contain:
//
// - SessionPublicId;
// - SessionRefreshTokenHash;
// - tokenFamilyPublicId.
//
// The refresh token is generated inside the login workflow.
//
// Only the resulting hash crosses the Session aggregate boundary.
//
// The raw refresh token remains transient and is returned only as part of
// the successful login response.
//
// -----------------------------------------------------------------------------
//
// Token generation:
//
// The command does not accept or generate authentication tokens.
//
// The login workflow is responsible for:
//
//     refresh token
//          │
//          ▼
//     refresh token hash
//          │
//          ▼
//       Session
//
// and:
//
//     authenticated login context
//          │
//          ▼
//       access token
//
// The raw refresh token MUST NOT be persisted, logged, published, or included
// in domain events.
//
// -----------------------------------------------------------------------------
//
// Correlation / causation:
//
// - correlationId identifies the complete login operation;
// - causationId optionally identifies the command or domain event that caused
//   this login operation.
//
// Direct HTTP login requests should generate correlationId at the presentation
// boundary and normally omit causationId.
//
// These values are propagated to resulting domain operations and events.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Authentication — Domain Value Objects
// -----------------------------------------------------------------------------

import type {
  DeviceFingerprint,
  DeviceName,
  DevicePlatform,
  DeviceOperatingSystem,
  DeviceOperatingSystemVersion,
  DeviceBrowser,
  DeviceBrowserVersion,
  DeviceType,
  SessionIpAddress,
  SessionUserAgent,
  SessionCountryCode,
  SessionCity,
} from '../../domain/value-objects';

// =============================================================================
// Command
// =============================================================================

/**
 * Command for executing the complete user login workflow.
 *
 * The command represents application intent only. It does not perform
 * authentication, persistence, token generation, or aggregate mutation.
 *
 * Required application inputs:
 *
 * - emailOrPhoneNumber;
 * - password;
 * - fingerprint;
 * - deviceType;
 * - correlationId.
 *
 * Optional:
 *
 * - device metadata;
 * - session context;
 * - causationId.
 *
 * The command intentionally does NOT accept:
 *
 * - identityPublicId;
 * - authenticationPublicId;
 * - devicePublicId;
 * - sessionPublicId;
 * - tokenFamilyPublicId;
 * - refreshToken;
 * - refreshTokenHash;
 * - accessToken.
 *
 * Those values are resolved or generated by the login workflow.
 */
export class AuthenticateLoginCommand extends Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    // -------------------------------------------------------------------------
    // Credentials
    // -------------------------------------------------------------------------

    /**
     * Email address or phone number supplied as the login identifier.
     *
     * The authentication workflow uses this value to resolve the authoritative
     * Identity and corresponding Authentication aggregate.
     *
     * This value is transient request input and must not be persisted as part
     * of the command itself.
     */
    public readonly emailOrPhoneNumber: string,

    /**
     * Transient plaintext password supplied by the login request.
     *
     * This value MUST never be:
     *
     * - persisted;
     * - logged;
     * - published;
     * - included in domain events;
     * - stored on an aggregate.
     */
    public readonly password: string,

    // -------------------------------------------------------------------------
    // Device
    // -------------------------------------------------------------------------

    /**
     * Opaque stable device fingerprint.
     *
     * The login workflow uses this value to locate an existing Device for the
     * authenticated Identity or to create a new Device.
     *
     * The command does not generate, derive, or interpret the fingerprint.
     */
    public readonly fingerprint: DeviceFingerprint,

    /**
     * Device category.
     */
    public readonly deviceType: DeviceType,

    /**
     * Optional human-readable device name.
     */
    public readonly deviceName: DeviceName | undefined,

    /**
     * Optional device platform.
     */
    public readonly platform: DevicePlatform | undefined,

    /**
     * Optional operating system.
     */
    public readonly operatingSystem: DeviceOperatingSystem | undefined,

    /**
     * Optional operating system version.
     */
    public readonly operatingSystemVersion:
      DeviceOperatingSystemVersion | undefined,

    /**
     * Optional browser name.
     */
    public readonly browser: DeviceBrowser | undefined,

    /**
     * Optional browser version.
     */
    public readonly browserVersion: DeviceBrowserVersion | undefined,

    // -------------------------------------------------------------------------
    // Session Context
    // -------------------------------------------------------------------------

    /**
     * Optional client IP address associated with the login.
     *
     * This is session context and is not used as an authentication credential.
     */
    public readonly ipAddress: SessionIpAddress | undefined,

    /**
     * Optional HTTP User-Agent associated with the login.
     *
     * This is session context supplied to Session creation.
     */
    public readonly userAgent: SessionUserAgent | undefined,

    /**
     * Optional ISO country code associated with the login.
     *
     * This is session context supplied to Session creation.
     */
    public readonly countryCode: SessionCountryCode | undefined,

    /**
     * Optional city associated with the login.
     *
     * This is session context supplied to Session creation.
     */
    public readonly city: SessionCity | undefined,

    // -------------------------------------------------------------------------
    // Application Metadata
    // -------------------------------------------------------------------------

    /**
     * Correlation identifier for the complete login operation.
     *
     * This identifies the end-to-end workflow:
     *
     *     authentication
     *          ↓
     *       device
     *          ↓
     *       session
     *          ↓
     *        tokens
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or domain event that caused this
     * login operation.
     */
    public readonly causationId?: string,
  ) {
    super();
  }
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default AuthenticateLoginCommand;
