// -----------------------------------------------------------------------------
// OTP Challenge — Create Command
// -----------------------------------------------------------------------------
//
// Application command for creating an OTP Challenge aggregate.
//
// The command represents the application-level intent:
//
//     Create OTP Challenge
//
// OtpChallenge is an independent aggregate responsible for one OTP
// verification challenge associated with an Identity.
//
// The command carries domain-ready value objects rather than raw transport
// primitives.
//
// DTO-to-domain conversion belongs at the presentation/application boundary.
//
// OTP generation and hashing belong to the application/security workflow.
// The generated OTP itself must never enter this command or the domain.
//
// -----------------------------------------------------------------------------
//
// Application responsibilities:
//
// The command handler is responsible for:
//
// - validating the command;
// - generating the OTP through security infrastructure;
// - hashing the generated OTP through security infrastructure;
// - converting the resulting hash into OtpChallengeOtpHash;
// - creating the OtpChallengeEntity through its domain factory;
// - creating the OtpChallengeAggregate;
// - recording OtpChallengeCreatedEvent;
// - persisting the aggregate;
// - coordinating OTP delivery when required.
//
// -----------------------------------------------------------------------------
//
// Domain responsibilities:
//
// The domain is responsible for:
//
// - generating OtpChallengePublicId;
// - generating the internal entity identity;
// - establishing the initial challenge lifecycle state;
// - initializing attempts;
// - validating domain invariants;
// - enforcing aggregate consistency;
// - recording domain events.
//
// -----------------------------------------------------------------------------
//
// This command does NOT:
//
// - validate Identity domain state;
// - generate OTPs itself;
// - hash OTPs itself;
// - contain a raw OTP;
// - contain an OTP hash;
// - send OTPs;
// - send notifications;
// - authenticate users;
// - create Sessions;
// - modify Authentication;
// - modify Recovery;
// - access Prisma;
// - persist the aggregate directly.
//
// Cross-aggregate orchestration belongs to the application layer.
//
// -----------------------------------------------------------------------------
//
// Required domain inputs:
//
// - identityPublicId;
// - purpose;
// - destination;
// - maxAttempts;
// - expiresAt;
// - correlationId.
//
// The following are intentionally NOT supplied:
//
// - raw OTP;
// - otpHash;
// - OtpChallengePublicId;
// - persistence/internal ID;
// - initial status;
// - attempts;
// - createdAt;
// - updatedAt;
// - verifiedAt.
//
// These values are generated or established by the appropriate application
// or domain boundary.
//
// -----------------------------------------------------------------------------
//
// Security boundary:
//
// Raw OTP values must never enter this command.
//
// In particular, the raw OTP must never:
//
// - be stored in the command;
// - be stored in the entity;
// - be stored in the aggregate;
// - be stored in the database;
// - be included in a domain event;
// - be logged.
//
// The OTP hash is generated by the application/security workflow immediately
// before aggregate creation and is passed directly into the domain factory.
//
// -----------------------------------------------------------------------------
//
// Correlation:
//
// correlationId is required.
// causationId is optional.
//
// Both identifiers belong to application/domain-event metadata and are not
// part of the OTP Challenge business state.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Domain Value Objects
// -----------------------------------------------------------------------------

import type {
  OtpChallengeIdentityPublicId,
  OtpChallengePurpose,
  OtpChallengeDestination,
  OtpChallengeMaxAttempts,
  OtpChallengeExpiresAt,
} from '../../domain/value-objects';

// =============================================================================
// Command
// =============================================================================

/**
 * Command for creating an OTP Challenge aggregate.
 *
 * The command contains only the domain-ready values required to request
 * creation of a new OTP Challenge.
 *
 * OTP material is deliberately excluded.
 *
 * The application handler generates the OTP and creates its hash before
 * invoking the domain entity factory.
 */
export class CreateOtpChallengeCommand extends Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    /**
     * Opaque public reference to the Identity associated with this
     * OTP Challenge.
     *
     * Cross-domain Identity validation does not occur inside this command.
     */
    public readonly identityPublicId: OtpChallengeIdentityPublicId,

    /**
     * Business purpose of the OTP Challenge.
     */
    public readonly purpose: OtpChallengePurpose,

    /**
     * Destination snapshot associated with the OTP Challenge.
     *
     * The destination may contain sensitive delivery information.
     *
     * It remains part of the OTP Challenge aggregate state and must not be
     * exposed through domain events unless explicitly modeled as safe.
     */
    public readonly destination: OtpChallengeDestination,

    /**
     * Maximum number of verification attempts allowed.
     *
     * The domain entity validates the actual invariant.
     */
    public readonly maxAttempts: OtpChallengeMaxAttempts,

    /**
     * Timestamp at which the OTP Challenge expires.
     *
     * The domain entity validates that this timestamp is after creation.
     */
    public readonly expiresAt: OtpChallengeExpiresAt,

    /**
     * Correlation identifier for the complete OTP Challenge operation.
     *
     * This value is propagated to OtpChallengeCreatedEvent.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or domain event that caused this
     * command.
     *
     * This value is propagated to OtpChallengeCreatedEvent when supplied.
     */
    public readonly causationId?: string,
  ) {
    super();
  }
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default CreateOtpChallengeCommand;
