// -----------------------------------------------------------------------------
// sisiMove — Update Travel Corridor Schema
// -----------------------------------------------------------------------------
//
// Validation schema for updating an authenticated Traveller Profile
// frequent-travel corridor.
//
// Responsibilities:
// - Validate user-editable corridor information.
// - Define the frontend write contract for corridor updates.
// - Validate geographic coordinates.
//
// Non-responsibilities:
// - Loading the existing corridor.
// - Resolving places or coordinates.
// - Generating corridor keys.
// - Determining corridor ownership.
// - Persisting the corridor.
// - Authorizing corridor updates.
// - Enforcing primary-corridor uniqueness.
//
// The backend remains authoritative for authorization, normalization,
// uniqueness, matching, and persistence.
//
// -----------------------------------------------------------------------------

import { z } from "zod";

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const CORRIDOR_NAME_MAX_LENGTH = 100;

const LATITUDE_MIN = -90;
const LATITUDE_MAX = 90;

const LONGITUDE_MIN = -180;
const LONGITUDE_MAX = 180;

// -----------------------------------------------------------------------------
// Schema
// -----------------------------------------------------------------------------

export const updateTravelCorridorSchema = z.object({
  /**
   * Human-readable origin name.
   *
   * Example:
   *   Nairobi
   */
  originName: z
    .string()
    .trim()
    .min(1, "Origin is required.")
    .max(
      CORRIDOR_NAME_MAX_LENGTH,
      `Origin must not exceed ${CORRIDOR_NAME_MAX_LENGTH} characters.`,
    ),

  /**
   * Human-readable destination name.
   *
   * Example:
   *   Mombasa
   */
  destinationName: z
    .string()
    .trim()
    .min(1, "Destination is required.")
    .max(
      CORRIDOR_NAME_MAX_LENGTH,
      `Destination must not exceed ${CORRIDOR_NAME_MAX_LENGTH} characters.`,
    ),

  /**
   * Geographic latitude of the origin.
   */
  originLatitude: z
    .number()
    .finite("Origin latitude must be a valid number.")
    .min(
      LATITUDE_MIN,
      `Origin latitude must be at least ${LATITUDE_MIN}.`,
    )
    .max(
      LATITUDE_MAX,
      `Origin latitude must not exceed ${LATITUDE_MAX}.`,
    ),

  /**
   * Geographic longitude of the origin.
   */
  originLongitude: z
    .number()
    .finite("Origin longitude must be a valid number.")
    .min(
      LONGITUDE_MIN,
      `Origin longitude must be at least ${LONGITUDE_MIN}.`,
    )
    .max(
      LONGITUDE_MAX,
      `Origin longitude must not exceed ${LONGITUDE_MAX}.`,
    ),

  /**
   * Geographic latitude of the destination.
   */
  destinationLatitude: z
    .number()
    .finite("Destination latitude must be a valid number.")
    .min(
      LATITUDE_MIN,
      `Destination latitude must be at least ${LATITUDE_MIN}.`,
    )
    .max(
      LATITUDE_MAX,
      `Destination latitude must not exceed ${LATITUDE_MAX}.`,
    ),

  /**
   * Geographic longitude of the destination.
   */
  destinationLongitude: z
    .number()
    .finite("Destination longitude must be a valid number.")
    .min(
      LONGITUDE_MIN,
      `Destination longitude must be at least ${LONGITUDE_MIN}.`,
    )
    .max(
      LONGITUDE_MAX,
      `Destination longitude must not exceed ${LONGITUDE_MAX}.`,
    ),

  /**
   * Optional stable corridor discovery/matching identifier.
   *
   * This is not a Journey public ID and is not generated by the frontend.
   */
  corridorKey: z
    .string()
    .trim()
    .min(1, "Corridor key cannot be empty.")
    .nullable()
    .optional(),

  /**
   * Whether this corridor should be the traveller's primary corridor.
   *
   * The backend remains responsible for ensuring that a profile has at most
   * one primary corridor.
   */
  isPrimary: z.boolean(),
});

// -----------------------------------------------------------------------------
// Inferred Type
// -----------------------------------------------------------------------------

export type UpdateTravelCorridorInput = z.infer<
  typeof updateTravelCorridorSchema
>;