// -----------------------------------------------------------------------------
// Identity — Role HTTP Controller
// -----------------------------------------------------------------------------
//
// REST controller for Role aggregate operations.
//
// Aggregate boundary:
//
//     RoleAggregate
//     └── RoleEntity
//
// Responsibilities:
//
// - HTTP transport;
// - DTO binding and validation;
// - conversion of transport primitives to domain value objects;
// - construction of application commands and queries;
// - dispatching application commands and queries;
// - mapping application/domain results into HTTP response models.
//
// This controller contains NO business rules.
//
// -----------------------------------------------------------------------------
//
// DOMAIN BOUNDARY
// -----------------------------------------------------------------------------
//
// RoleAggregate owns:
//
//     RoleEntity
//
// Role is an aggregate root.
//
// Role relationships remain separate aggregate boundaries:
//
//     IdentityAggregate
//     └── IdentityEntity
//         └── IdentityRoleEntity[]
//
//     RolePermissionAggregate
//     └── RolePermissionEntity
//
// Referenced aggregates are coordinated through application-layer use cases.
//
// -----------------------------------------------------------------------------
//
// IMPORTANT
// -----------------------------------------------------------------------------
//
// This controller does NOT:
//
// - assign Roles to Identities;
// - revoke Roles from Identities;
// - assign Permissions to Roles;
// - revoke Permissions from Roles;
// - evaluate authorization;
// - access Prisma;
// - access repositories;
// - directly mutate RoleAggregate;
// - determine system-role protection;
// - determine role eligibility;
// - determine lifecycle invariants.
//
// Those responsibilities belong to their respective application/domain
// boundaries.
//
// -----------------------------------------------------------------------------
//
// SUPPORTED OPERATIONS
// -----------------------------------------------------------------------------
//
// Role definition:
//
//     POST /roles
//
// Role queries:
//
//     GET /roles
//     GET /roles/:rolePublicId
//
// Role lifecycle:
//
//     PATCH /roles/:rolePublicId/activate
//     PATCH /roles/:rolePublicId/deactivate
//
// -----------------------------------------------------------------------------
//
// SECURITY MODEL
// -----------------------------------------------------------------------------
//
// Role definitions are authorization infrastructure.
//
// All Role endpoints therefore require authentication and authorization.
//
// Authentication:
//
//     JwtAuthGuard
//
// Authorization:
//
//     PermissionsGuard
//     @RequirePermissions(...)
//
// Required permissions:
//
//     role:read
//     role:create
//     role:activate
//     role:deactivate
//
// Guards are intentionally applied per endpoint.
//
// There is NO class-level @UseGuards declaration.
//
// This keeps every endpoint's security boundary explicit.
//
// -----------------------------------------------------------------------------
//
// ROLE QUERIES
// -----------------------------------------------------------------------------
//
// GET /roles
//
// Supported transport filters:
//
//     isActive
//     isSystem
//     assignable
//     orderByDisplayOrder
//
// DTO values are translated into the application-level:
//
//     GetRolesQueryFilters
//
// The controller does not interpret the meaning of these filters.
//
// -----------------------------------------------------------------------------
//
// ROLE CREATION
// -----------------------------------------------------------------------------
//
// POST /roles
//
// The client supplies business definition data:
//
//     code
//     name
//     displayOrder
//     isSystem
//     description
//
// The client does NOT supply:
//
//     rolePublicId
//     createdAt
//     updatedAt
//     correlationId
//     causationId
//
// RolePublicId is generated by the domain/application creation process.
//
// Domain timestamps are generated by the appropriate domain/application
// boundary.
//
// -----------------------------------------------------------------------------
//
// ROLE LIFECYCLE
// -----------------------------------------------------------------------------
//
// Activation:
//
//     PATCH /roles/:rolePublicId/activate
//
// Deactivation:
//
//     PATCH /roles/:rolePublicId/deactivate
//
// The client supplies only the target RolePublicId.
//
// The client does NOT supply:
//
//     activatedAt
//     deactivatedAt
//     correlationId
//     causationId
//
// Lifecycle timestamps are domain facts.
//
// Therefore:
//
//     activatedAt
//     deactivatedAt
//
// are determined by the Role aggregate/application workflow.
//
// Rules such as:
//
// - already-active behavior;
// - already-inactive behavior;
// - system-role protection;
// - lifecycle invariants;
//
// remain inside the domain/application layer.
//
// -----------------------------------------------------------------------------
//
// APPLICATION MESSAGE METADATA
// -----------------------------------------------------------------------------
//
// Direct HTTP commands are root application operations.
//
// Therefore:
//
//     correlationId = randomUUID()
//
// is generated by this controller.
//
// The client does NOT control correlation metadata.
//
// causationId is intentionally omitted.
//
// If a trusted internal workflow requires causation metadata, that workflow
// should invoke the application layer directly rather than forwarding an
// arbitrary client-provided causation ID through HTTP.
//
// -----------------------------------------------------------------------------
//
// DOMAIN VALUE OBJECTS
// -----------------------------------------------------------------------------
//
// Transport primitives are converted before entering the application layer:
//
//     code
//         └── RoleCode
//
//     name
//         └── RoleName
//
//     rolePublicId
//         └── RolePublicId
//
// This keeps transport DTOs independent from domain behavior while ensuring
// commands receive validated domain representations.
//
// -----------------------------------------------------------------------------
//
// SECURITY BOUNDARY
// -----------------------------------------------------------------------------
//
// This controller does NOT:
//
// - verify JWTs;
// - decode JWTs;
// - inspect Authorization headers;
// - resolve permissions;
// - evaluate authorization;
// - access Prisma;
// - access repositories;
// - directly mutate RoleAggregate;
// - generate domain lifecycle timestamps;
// - assign Roles to Identities;
// - revoke Roles from Identities;
// - assign Permissions to Roles;
// - revoke Permissions from Roles.
//
// =============================================================================

// -----------------------------------------------------------------------------
// Node
// -----------------------------------------------------------------------------

import { randomUUID } from 'node:crypto';

// -----------------------------------------------------------------------------
// NestJS
// -----------------------------------------------------------------------------

import {
  Body,
  Controller,
  Get,
  Inject,
  Param,
  Patch,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';

// -----------------------------------------------------------------------------
// Swagger
// -----------------------------------------------------------------------------

import {
  ApiBearerAuth,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiTags,
} from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Identity — Authentication & Authorization
// -----------------------------------------------------------------------------

import {
  JwtAuthGuard,
  PermissionsGuard,
  RequirePermissions,
} from '../../../../../foundation/security/auth';

// -----------------------------------------------------------------------------
// Foundation — Application
// -----------------------------------------------------------------------------

import type { CommandHandler } from '../../../../../foundation/kernel/application/command-handler';

import type { QueryHandler } from '../../../../../foundation/kernel/application/query-handler';

// -----------------------------------------------------------------------------
// Application — Tokens
// -----------------------------------------------------------------------------

import { IDENTITY_TOKENS } from '../../../application/identity.tokens';

// -----------------------------------------------------------------------------
// Application — Commands
// -----------------------------------------------------------------------------

import {
  ActivateRoleCommand,
  CreateRoleCommand,
  DeactivateRoleCommand,
} from '../../../application/commands';

// -----------------------------------------------------------------------------
// Application — Queries
// -----------------------------------------------------------------------------

import {
  GetRoleQuery,
  GetRolesQuery,
  GetRolesQueryFilters,
} from '../../../application/queries';

// -----------------------------------------------------------------------------
// Domain — Aggregate
// -----------------------------------------------------------------------------

import type { RoleAggregate } from '../../../domain/aggregates/role.aggregate';

// -----------------------------------------------------------------------------
// Domain — Value Objects
// -----------------------------------------------------------------------------

import {
  RoleCode,
  RoleName,
  RolePublicId,
} from '../../../domain/value-objects';

// -----------------------------------------------------------------------------
// Presentation — Request DTOs
// -----------------------------------------------------------------------------

import { CreateRoleRequestDto } from '../dto/request';

// -----------------------------------------------------------------------------
// Presentation — Query DTOs
// -----------------------------------------------------------------------------

import { GetRoleQueryDto, GetRolesQueryDto } from '../queries';

// -----------------------------------------------------------------------------
// Presentation — Response Models
// -----------------------------------------------------------------------------

import type { RoleResponse } from '../mappers/role.response.mapper';

// -----------------------------------------------------------------------------
// Presentation — Response Mapper
// -----------------------------------------------------------------------------

import { RoleResponseMapper } from '../mappers/role.response.mapper';

// =============================================================================
// Controller
// =============================================================================

@ApiTags('Roles')
@Controller('roles')
export class RolesController {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    // -------------------------------------------------------------------------
    // Role Command Handlers
    // -------------------------------------------------------------------------

    @Inject(IDENTITY_TOKENS.COMMAND_HANDLERS.CREATE_ROLE)
    private readonly createRoleHandler: CommandHandler<
      CreateRoleCommand,
      RoleAggregate
    >,

    @Inject(IDENTITY_TOKENS.COMMAND_HANDLERS.ACTIVATE_ROLE)
    private readonly activateRoleHandler: CommandHandler<
      ActivateRoleCommand,
      RoleAggregate
    >,

    @Inject(IDENTITY_TOKENS.COMMAND_HANDLERS.DEACTIVATE_ROLE)
    private readonly deactivateRoleHandler: CommandHandler<
      DeactivateRoleCommand,
      RoleAggregate
    >,

    // -------------------------------------------------------------------------
    // Role Query Handlers
    // -------------------------------------------------------------------------

    @Inject(IDENTITY_TOKENS.QUERY_HANDLERS.GET_ROLE)
    private readonly getRoleHandler: QueryHandler<
      GetRoleQuery,
      RoleAggregate | null
    >,

    @Inject(IDENTITY_TOKENS.QUERY_HANDLERS.GET_ROLES)
    private readonly getRolesHandler: QueryHandler<
      GetRolesQuery,
      readonly RoleAggregate[]
    >,
  ) {}

  // ===========================================================================
  // Queries
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Get Roles
  // ---------------------------------------------------------------------------
  //
  // GET /roles
  //
  // Returns Role aggregates matching the supplied application-level filters.
  //
  // ---------------------------------------------------------------------------

  @Get()
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'List roles',
    description:
      'Returns Role aggregates matching the supplied role filters. Role definitions are authorization infrastructure and require the role:read permission.',
  })
  @ApiQuery({
    name: 'isActive',
    required: false,
    type: Boolean,
    description: 'Filter roles by active status.',
  })
  @ApiQuery({
    name: 'isSystem',
    required: false,
    type: Boolean,
    description: 'Filter roles by system-role status.',
  })
  @ApiQuery({
    name: 'assignable',
    required: false,
    type: Boolean,
    description: 'Filter roles by assignability.',
  })
  @ApiQuery({
    name: 'orderByDisplayOrder',
    required: false,
    type: Boolean,
    description: 'Order results by display order when enabled.',
  })
  @UseGuards(JwtAuthGuard, PermissionsGuard)
  @RequirePermissions('role:read')
  public async getMany(
    @Query() dto: GetRolesQueryDto,
  ): Promise<RoleResponse[]> {
    const filters: GetRolesQueryFilters = {};

    if (dto.isActive !== undefined) {
      filters.isActive = dto.isActive;
    }

    if (dto.isSystem !== undefined) {
      filters.isSystem = dto.isSystem;
    }

    if (dto.assignable !== undefined) {
      filters.assignable = dto.assignable;
    }

    if (dto.orderByDisplayOrder !== undefined) {
      filters.orderByDisplayOrder = dto.orderByDisplayOrder;
    }

    const query = new GetRolesQuery(filters);

    const aggregates = await this.getRolesHandler.execute(query);

    return aggregates.map((aggregate) =>
      RoleResponseMapper.toResponse(aggregate),
    );
  }

  // ---------------------------------------------------------------------------
  // Get Role
  // ---------------------------------------------------------------------------
  //
  // GET /roles/:rolePublicId
  //
  // Resolves one Role aggregate through its canonical public identifier.
  //
  // The public identifier is not an authorization credential.
  //
  // ---------------------------------------------------------------------------

  @Get(':rolePublicId')
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get role',
    description:
      'Returns a single Role aggregate identified by its public identifier.',
  })
  @ApiParam({
    name: 'rolePublicId',
    type: String,
    required: true,
    description: 'Public ID of the Role aggregate.',
    example: 'ROL-8VBLAO',
  })
  @UseGuards(JwtAuthGuard, PermissionsGuard)
  @RequirePermissions('role:read')
  public async get(
    @Param() dto: GetRoleQueryDto,
  ): Promise<RoleResponse | null> {
    const query = new GetRoleQuery(new RolePublicId(dto.rolePublicId));

    const aggregate = await this.getRoleHandler.execute(query);

    if (aggregate === null) {
      return null;
    }

    return RoleResponseMapper.toResponse(aggregate);
  }

  // ===========================================================================
  // Commands
  // ===========================================================================

  // ---------------------------------------------------------------------------
  // Create Role
  // ---------------------------------------------------------------------------
  //
  // POST /roles
  //
  // ---------------------------------------------------------------------------

  @Post()
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Create role',
    description:
      'Creates a new Role definition. The role public identifier and domain timestamps are generated by the application/domain workflow.',
  })
  @UseGuards(JwtAuthGuard, PermissionsGuard)
  @RequirePermissions('role:create')
  public async create(
    @Body() dto: CreateRoleRequestDto,
  ): Promise<RoleResponse> {
    const command = new CreateRoleCommand(
      RoleCode.create(dto.code),

      RoleName.create(dto.name),

      dto.displayOrder,

      dto.isSystem,

      dto.description,

      randomUUID(),
    );

    const aggregate = await this.createRoleHandler.execute(command);

    return RoleResponseMapper.toResponse(aggregate);
  }

  // ---------------------------------------------------------------------------
  // Activate Role
  // ---------------------------------------------------------------------------
  //
  // PATCH /roles/:rolePublicId/activate
  //
  // ---------------------------------------------------------------------------

  @Patch(':rolePublicId/activate')
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Activate role',
    description:
      'Activates the specified Role. Lifecycle rules, system-role protection, and effective lifecycle timestamps remain inside the application/domain boundary.',
  })
  @ApiParam({
    name: 'rolePublicId',
    type: String,
    required: true,
    description: 'Public ID of the Role aggregate to activate.',
    example: 'ROL-8VBLAO',
  })
  @UseGuards(JwtAuthGuard, PermissionsGuard)
  @RequirePermissions('role:activate')
  public async activate(
    @Param('rolePublicId') rolePublicId: string,
  ): Promise<RoleResponse> {
    const command = new ActivateRoleCommand(
      new RolePublicId(rolePublicId),

      randomUUID(),
    );

    const aggregate = await this.activateRoleHandler.execute(command);

    return RoleResponseMapper.toResponse(aggregate);
  }

  // ---------------------------------------------------------------------------
  // Deactivate Role
  // ---------------------------------------------------------------------------
  //
  // PATCH /roles/:rolePublicId/deactivate
  //
  // ---------------------------------------------------------------------------

  @Patch(':rolePublicId/deactivate')
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Deactivate role',
    description:
      'Deactivates the specified Role. Lifecycle rules, system-role protection, and effective lifecycle timestamps remain inside the application/domain boundary.',
  })
  @ApiParam({
    name: 'rolePublicId',
    type: String,
    required: true,
    description: 'Public ID of the Role aggregate to deactivate.',
    example: 'ROL-8VBLAO',
  })
  @UseGuards(JwtAuthGuard, PermissionsGuard)
  @RequirePermissions('role:deactivate')
  public async deactivate(
    @Param('rolePublicId') rolePublicId: string,
  ): Promise<RoleResponse> {
    const command = new DeactivateRoleCommand(
      new RolePublicId(rolePublicId),

      randomUUID(),
    );

    const aggregate = await this.deactivateRoleHandler.execute(command);

    return RoleResponseMapper.toResponse(aggregate);
  }
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default RolesController;
