// -----------------------------------------------------------------------------
// Infrastructure — Security Module
// -----------------------------------------------------------------------------
//
// Composition root for infrastructure security services.
//
// Provides:
//
// - encryption;
// - password hashing;
// - generic opaque token generation;
// - refresh token hashing;
// - recovery token hashing;
// - recovery token generation/service;
// - OTP generation, hashing, and verification;
// - JWT token service;
// - JWT authentication strategy.
//
// -----------------------------------------------------------------------------
//
// Security dependency graph:
//
//     PasswordHasher
//            │
//            ▼
//     BcryptPasswordService
//            │
//            ├──────────────────────┐
//            │                      │
//            ▼                      ▼
//     RecoveryTokenHasher       CryptoOtpService
//            │                      │
//            ▼                      ▼
//     RecoveryTokenService      OtpService
//
//     TokenGenerator
//            │
//            ├──────────────► RecoveryTokenService
//            │
//            ▼
//     opaque token generation
//
//     RefreshTokenHasher
//            │
//            ▼
//     RefreshTokenHasherService
//
//     JwtService
//            │
//            ▼
//     JwtTokenService
//            │
//            ▼
//       JwtStrategy
//
// -----------------------------------------------------------------------------
//
// REFRESH TOKENS:
//
// Refresh tokens are opaque bearer credentials.
//
// Their responsibilities are deliberately split:
//
//     TokenGenerator
//          │
//          ▼
//     raw refresh token
//          │
//          ├──────────────► returned once to client
//          │
//          ▼
//     RefreshTokenHasher
//          │
//          ▼
//     SessionRefreshTokenHash
//          │
//          ▼
//     Session
//
// The raw refresh token is never persisted.
//
// Refresh-token hashing is intentionally separate from:
//
// - PasswordHasher;
// - RecoveryTokenHasher;
// - JwtTokenService.
//
// This keeps credential semantics explicit at the infrastructure boundary.
//
// -----------------------------------------------------------------------------
//
// IMPORTANT:
//
// Security abstractions remain defined in Foundation.
//
// Infrastructure owns:
//
// - concrete implementations;
// - infrastructure DI tokens;
// - NestJS provider registration;
// - external security framework configuration.
//
// Application and domain layers must not import concrete infrastructure
// security implementations directly.
//
// -----------------------------------------------------------------------------
//
// MODULE BOUNDARY:
//
// Consumers should import SecurityModule and consume the exported
// infrastructure tokens.
//
// Example:
//
//     AuthenticationModule
//             │
//             ▼
//        SecurityModule
//             │
//             ├── SECURITY_PASSWORD_HASHER
//             ├── SECURITY_TOKEN_GENERATOR
//             ├── SECURITY_REFRESH_TOKEN_HASHER
//             ├── SECURITY_RECOVERY_TOKEN_SERVICE
//             └── SECURITY_OTP_SERVICE
//
// Authentication application handlers should NOT inject these infrastructure
// tokens directly. AuthModule's application DI layer should bridge them:
//
//     AUTH_TOKENS.APPLICATION_SERVICES.PASSWORD_HASHER
//                 │
//                 ▼
//     SECURITY_PASSWORD_HASHER
//
//     AUTH_TOKENS.APPLICATION_SERVICES.TOKEN_GENERATOR
//                 │
//                 ▼
//     SECURITY_TOKEN_GENERATOR
//
//     AUTH_TOKENS.APPLICATION_SERVICES.REFRESH_TOKEN_HASHER
//                 │
//                 ▼
//     SECURITY_REFRESH_TOKEN_HASHER
//
// -----------------------------------------------------------------------------
//
// JWT:
//
// Access tokens are JWTs.
//
// Refresh tokens remain opaque credentials and are NOT generated by the JWT
// service.
//
// JwtTokenService is responsible only for access-token signing, verification,
// and decoding.
//
// -----------------------------------------------------------------------------
//
// PROVIDER OWNERSHIP:
//
// securityProviders is the single infrastructure provider collection for:
//
// - AesEncryptionService;
// - BcryptPasswordService;
// - CryptoTokenGeneratorService;
// - RefreshTokenHasherService;
// - RecoveryTokenHasherService;
// - InfrastructureRecoveryTokenService;
// - CryptoOtpService;
// - JwtTokenService.
//
// JwtStrategy is registered separately because it is an authentication
// framework strategy rather than a Foundation security abstraction.
//
// -----------------------------------------------------------------------------

import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';

// -----------------------------------------------------------------------------
// Infrastructure — Security
// -----------------------------------------------------------------------------

import { JwtStrategy } from './jwt.strategy';
import { securityProviders } from './security.providers';

// =============================================================================
// Security Module
// =============================================================================

@Module({
  // ===========================================================================
  // Imports
  // ===========================================================================
  //
  // PassportModule:
  //
  //     Provides Passport integration required by JwtStrategy.
  //
  // JwtModule:
  //
  //     Provides NestJS JwtService used internally by JwtTokenService.
  //
  // ---------------------------------------------------------------------------

  imports: [
    PassportModule,

    JwtModule.registerAsync({
      useFactory: () => {
        // ---------------------------------------------------------------------
        // JWT configuration
        // ---------------------------------------------------------------------

        const secret = process.env.JWT_ACCESS_SECRET?.trim();
        const issuer = process.env.JWT_ISSUER?.trim();
        const audience = process.env.JWT_AUDIENCE?.trim();

        // ---------------------------------------------------------------------
        // Secret
        // ---------------------------------------------------------------------

        if (!secret) {
          throw new Error('JWT_ACCESS_SECRET is required.');
        }

        if (secret.length < 32) {
          throw new Error(
            'JWT_ACCESS_SECRET must contain at least 32 characters.',
          );
        }

        // ---------------------------------------------------------------------
        // Issuer
        // ---------------------------------------------------------------------

        if (!issuer) {
          throw new Error('JWT_ISSUER is required.');
        }

        // ---------------------------------------------------------------------
        // Audience
        // ---------------------------------------------------------------------

        if (!audience) {
          throw new Error('JWT_AUDIENCE is required.');
        }

        // ---------------------------------------------------------------------
        // JWT configuration
        // ---------------------------------------------------------------------

        return {
          secret,

          signOptions: {
            algorithm: 'HS256',
            issuer,
            audience,
          },

          verifyOptions: {
            algorithms: ['HS256'],
            issuer,
            audience,
          },
        };
      },
    }),
  ],

  // ===========================================================================
  // Providers
  // ===========================================================================
  //
  // securityProviders contains the complete infrastructure security graph:
  //
  //     AesEncryptionService
  //     BcryptPasswordService
  //     CryptoTokenGeneratorService
  //     RefreshTokenHasherService
  //     RecoveryTokenHasherService
  //     InfrastructureRecoveryTokenService
  //     CryptoOtpService
  //     JwtTokenService
  //
  // JwtStrategy is registered separately because it is an authentication
  // strategy rather than a Foundation security abstraction.
  //
  // ---------------------------------------------------------------------------

  providers: [...securityProviders, JwtStrategy],

  // ===========================================================================
  // Exports
  // ===========================================================================
  //
  // Export securityProviders so consuming infrastructure/application modules
  // can access the configured infrastructure security tokens.
  //
  // In particular:
  //
  //     SECURITY_PASSWORD_HASHER
  //     SECURITY_TOKEN_GENERATOR
  //     SECURITY_REFRESH_TOKEN_HASHER
  //     SECURITY_RECOVERY_TOKEN_SERVICE
  //     SECURITY_OTP_SERVICE
  //
  // can be consumed by the Authentication infrastructure DI bridge.
  //
  // JwtStrategy is exported for authentication-module integration.
  //
  // JwtModule is exported because JwtTokenService depends on Nest's JwtService
  // and consuming modules may need the configured JWT module context.
  //
  // PassportModule is intentionally not exported. JwtStrategy belongs to the
  // Security infrastructure boundary and consuming modules do not need direct
  // access to Passport's module registration.
  //
  // ---------------------------------------------------------------------------

  exports: [...securityProviders, JwtStrategy, JwtModule],
})
export class SecurityModule {}
