// -----------------------------------------------------------------------------
// Infrastructure — Security — Dependency Injection Tokens
// -----------------------------------------------------------------------------
//
// Centralized infrastructure DI tokens.
//
// These tokens identify concrete infrastructure implementations of Foundation
// security abstractions.
//
// Keep these tokens in infrastructure because they belong to the composition
// root and identify infrastructure-provided implementations.
//
// Application layers must depend on their own application-facing tokens and
// abstractions rather than importing these infrastructure tokens directly.
//
// -----------------------------------------------------------------------------

// =============================================================================
// Encryption
// =============================================================================
//
// Foundation abstraction:
//
//     EncryptionService
//
// Infrastructure implementation:
//
//     AesEncryptionService
//
// -----------------------------------------------------------------------------

export const SECURITY_ENCRYPTION = Symbol('SECURITY_ENCRYPTION');

// =============================================================================
// Password Hashing
// =============================================================================
//
// Foundation abstraction:
//
//     PasswordHasher
//
// Infrastructure implementation:
//
//     BcryptPasswordService
//
// Password hashing is intentionally separate from refresh-token hashing.
//
// Passwords are user-chosen credentials and require an adaptive password
// hashing algorithm.
//
// -----------------------------------------------------------------------------

export const SECURITY_PASSWORD_HASHER = Symbol('SECURITY_PASSWORD_HASHER');

// =============================================================================
// Generic Token Generation
// =============================================================================
//
// Foundation abstraction:
//
//     TokenGenerator
//
// Infrastructure implementation:
//
//     CryptoTokenGeneratorService
//
// Generic token generation produces cryptographically secure, opaque,
// high-entropy bearer credentials.
//
// Examples:
//
//     - refresh tokens;
//     - recovery tokens;
//     - verification-style bearer credentials;
//     - other security tokens.
//
// OTP generation is deliberately handled separately by OtpService.
//
// -----------------------------------------------------------------------------

export const SECURITY_TOKEN_GENERATOR = Symbol('SECURITY_TOKEN_GENERATOR');

// =============================================================================
// Refresh Token Hashing
// =============================================================================
//
// Foundation abstraction:
//
//     RefreshTokenHasher
//
// Infrastructure implementation:
//
//     RefreshTokenHasherService
//
// Refresh tokens are high-entropy opaque bearer credentials generated by
// TokenGenerator.
//
// Their hashing lifecycle is:
//
//     TokenGenerator
//          │
//          ▼
//     Raw refresh token
//          │
//          ├──────────────────────────────► Client
//          │
//          ▼
//     RefreshTokenHasher
//          │
//          ▼
//     Cryptographic hash
//          │
//          ▼
//     SessionRefreshTokenHash
//          │
//          ▼
//     Session
//
// Refresh-token hashing is deliberately separate from PasswordHasher and
// RecoveryTokenHasher because each represents a distinct security boundary.
//
// -----------------------------------------------------------------------------

export const SECURITY_REFRESH_TOKEN_HASHER = Symbol(
  'SECURITY_REFRESH_TOKEN_HASHER',
);

// =============================================================================
// Recovery Token Hashing
// =============================================================================
//
// Foundation abstraction:
//
//     RecoveryTokenHasher
//
// Infrastructure implementation:
//
//     RecoveryTokenHasherService
//
// Recovery-token hashing remains independent from refresh-token hashing.
//
// -----------------------------------------------------------------------------

export const SECURITY_RECOVERY_TOKEN_HASHER = Symbol(
  'SECURITY_RECOVERY_TOKEN_HASHER',
);

// =============================================================================
// Recovery Token Service
// =============================================================================
//
// Foundation abstraction:
//
//     RecoveryTokenService
//
// Infrastructure implementation:
//
//     InfrastructureRecoveryTokenService
//
// This service composes:
//
//     TokenGenerator
//     RecoveryTokenHasher
//
// It owns the infrastructure mechanics for generating and hashing recovery
// tokens.
//
// -----------------------------------------------------------------------------

export const SECURITY_RECOVERY_TOKEN_SERVICE = Symbol(
  'SECURITY_RECOVERY_TOKEN_SERVICE',
);

// =============================================================================
// JWT Token Service
// =============================================================================
//
// Foundation abstraction:
//
//     JwtTokenService
//
// Infrastructure implementation:
//
//     JwtTokenService
//
// The concrete implementation internally uses NestJS JwtService.
//
// JWT access-token creation and verification remain separate from opaque
// refresh-token generation.
//
// -----------------------------------------------------------------------------

export const SECURITY_JWT_TOKEN_SERVICE = Symbol('SECURITY_JWT_TOKEN_SERVICE');

// =============================================================================
// OTP Service
// =============================================================================
//
// Foundation abstraction:
//
//     OtpService
//
// Infrastructure implementation:
//
//     CryptoOtpService
//
// OTP is deliberately separate from TokenGenerator.
//
// TokenGenerator:
//
//     - produces opaque high-entropy bearer tokens;
//     - is suitable for refresh/recovery/verification-style credentials.
//
// OtpService:
//
//     - produces numeric one-time passwords;
//     - uses cryptographically secure randomness;
//     - hashes OTPs;
//     - verifies raw OTPs against persisted hashes.
//
// The raw OTP is never persisted by the security infrastructure.
//
// -----------------------------------------------------------------------------

export const SECURITY_OTP_SERVICE = Symbol('SECURITY_OTP_SERVICE');
