// src/domains/identity/domain/value-objects/recovery-failure-reason.enum.ts

export enum RecoveryFailureReason {
  USER_CANCELLED = 'USER_CANCELLED',

  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_ALREADY_USED = 'TOKEN_ALREADY_USED',

  IDENTITY_NOT_FOUND = 'IDENTITY_NOT_FOUND',
  IDENTITY_NOT_ACTIVE = 'IDENTITY_NOT_ACTIVE',

  RECOVERY_ALREADY_COMPLETED = 'RECOVERY_ALREADY_COMPLETED',
  RECOVERY_ALREADY_CANCELLED = 'RECOVERY_ALREADY_CANCELLED',
  RECOVERY_EXPIRED = 'RECOVERY_EXPIRED',

  PASSWORD_POLICY_VIOLATION = 'PASSWORD_POLICY_VIOLATION',
  PASSWORD_REUSE = 'PASSWORD_REUSE',

  MFA_VALIDATION_FAILED = 'MFA_VALIDATION_FAILED',

  ADMIN_CANCELLED = 'ADMIN_CANCELLED',
  SECURITY_POLICY = 'SECURITY_POLICY',

  SYSTEM_ERROR = 'SYSTEM_ERROR',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
}
