// src/domains/journey-booking/application/handlers/create-journey-booking-snapshot.handler.ts

// -----------------------------------------------------------------------------
// Journey Booking Snapshot — Create Command Handler
// -----------------------------------------------------------------------------
//
// Application responsibilities:
//
// 1. Load the Journey Booking aggregate.
// 2. Fail with JourneyBookingNotFoundException when it does not exist.
// 3. Create the Journey Booking Snapshot entity.
// 4. Attach the snapshot to the Journey Booking aggregate.
// 5. Persist the changed aggregate.
// 6. Return the updated aggregate.
//
// Snapshot ownership and aggregate invariants remain inside the
// JourneyBookingAggregate.
//
// The snapshot public ID is generated by JourneyBookingSnapshotEntity.create().
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS
// -----------------------------------------------------------------------------

import { Inject, Injectable } from '@nestjs/common';

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import type { CommandHandler } from '../../../../foundation/kernel/application/command-handler';

// -----------------------------------------------------------------------------
// Command
// -----------------------------------------------------------------------------

import type { CreateJourneyBookingSnapshotCommand } from '../commands/create-journey-booking-snapshot.command';

// -----------------------------------------------------------------------------
// Aggregate
// -----------------------------------------------------------------------------

import type { JourneyBookingAggregate } from '../../domain/aggregates/journey-booking.aggregate';

// -----------------------------------------------------------------------------
// Entity
// -----------------------------------------------------------------------------

import { JourneyBookingSnapshotEntity } from '../../domain/entities/journey-booking-snapshot.entity';

// -----------------------------------------------------------------------------
// Exceptions
// -----------------------------------------------------------------------------

import { JourneyBookingNotFoundException } from '../../domain/exceptions';

// -----------------------------------------------------------------------------
// Repository
// -----------------------------------------------------------------------------

import type { JourneyBookingRepository } from '../../domain/repositories/journey-booking.repository';

// -----------------------------------------------------------------------------
// Dependency Injection Tokens
// -----------------------------------------------------------------------------

import { JOURNEY_BOOKING_TOKENS } from '../journey-booking.tokens';

// -----------------------------------------------------------------------------
// Handler
// -----------------------------------------------------------------------------

/**
 * Handles creation of the historical snapshot for an existing
 * Journey Booking.
 *
 * The handler is an application-layer orchestrator.
 *
 * It does NOT:
 *
 * - implement snapshot business rules;
 * - mutate the aggregate root directly;
 * - recreate aggregate invariants;
 * - contain persistence logic;
 * - communicate directly with infrastructure.
 *
 * Those responsibilities remain within their respective boundaries.
 *
 * The workflow is:
 *
 *     CreateJourneyBookingSnapshotCommand
 *                    ↓
 *     JourneyBookingRepository
 *                    ↓
 *     JourneyBookingAggregate
 *                    ↓
 *     JourneyBookingSnapshotEntity.create()
 *                    ↓
 *     aggregate.attachSnapshot()
 *                    ↓
 *     JourneyBookingRepository.save()
 *
 * The repository is resolved through:
 *
 *     JOURNEY_BOOKING_TOKENS.REPOSITORY
 */
@Injectable()
export class CreateJourneyBookingSnapshotHandler implements CommandHandler<
  CreateJourneyBookingSnapshotCommand,
  JourneyBookingAggregate
> {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  constructor(
    @Inject(JOURNEY_BOOKING_TOKENS.REPOSITORY)
    private readonly repository: JourneyBookingRepository,
  ) {}

  // ===========================================================================
  // Execute
  // ===========================================================================

  public async execute(
    command: CreateJourneyBookingSnapshotCommand,
  ): Promise<JourneyBookingAggregate> {
    // -------------------------------------------------------------------------
    // Load Aggregate
    // -------------------------------------------------------------------------

    const aggregate = await this.repository.findByPublicId(
      command.journeyBookingPublicId,
    );

    // -------------------------------------------------------------------------
    // Not Found
    // -------------------------------------------------------------------------

    if (aggregate === null) {
      throw new JourneyBookingNotFoundException(
        command.journeyBookingPublicId.value,
      );
    }

    // -------------------------------------------------------------------------
    // Create Snapshot
    // -------------------------------------------------------------------------
    //
    // The snapshot entity generates its own public identity.
    //

    const snapshot = JourneyBookingSnapshotEntity.create({
      originName: command.originName,

      destinationName: command.destinationName,

      originCoordinates: command.originCoordinates,

      destinationCoordinates: command.destinationCoordinates,

      departureAt: command.departureAt,

      arrivalAt: command.arrivalAt,

      timezone: command.timezone,

      vehicleMake: command.vehicleMake,

      vehicleModel: command.vehicleModel,

      vehicleYear: command.vehicleYear,

      vehicleColor: command.vehicleColor,

      vehicleRegistration: command.vehicleRegistration,
    });

    // -------------------------------------------------------------------------
    // Attach Snapshot
    // -------------------------------------------------------------------------
    //
    // The aggregate requires correlation metadata because attaching the
    // snapshot records a JourneyBookingSnapshotCreatedEvent.
    //

    aggregate.attachSnapshot(
      snapshot,
      command.correlationId,
      command.causationId,
    );

    // -------------------------------------------------------------------------
    // Persistence
    // -------------------------------------------------------------------------

    await this.repository.save(aggregate);

    // -------------------------------------------------------------------------
    // Result
    // -------------------------------------------------------------------------

    return aggregate;
  }
}
