// src/domains/journey-booking/application/handlers/set-journey-booking-pricing.handler.ts

// -----------------------------------------------------------------------------
// Journey Booking Pricing — Set Command Handler
// -----------------------------------------------------------------------------
//
// Application responsibilities:
//
// 1. Load the Journey Booking aggregate.
// 2. Fail with JourneyBookingNotFoundException when it does not exist.
// 3. Create the Journey Booking Pricing entity.
// 4. Attach the pricing to the Journey Booking aggregate.
// 5. Persist the changed aggregate.
// 6. Return the updated aggregate.
//
// Pricing ownership and aggregate invariants remain inside the
// JourneyBookingAggregate.
//
// The pricing public ID is generated by JourneyBookingPricingEntity.create().
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS
// -----------------------------------------------------------------------------

import { Inject, Injectable } from '@nestjs/common';

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import type { CommandHandler } from '../../../../foundation/kernel/application/command-handler';

// -----------------------------------------------------------------------------
// Command
// -----------------------------------------------------------------------------

import type { SetJourneyBookingPricingCommand } from '../commands/set-journey-booking-pricing.command';

// -----------------------------------------------------------------------------
// Aggregate
// -----------------------------------------------------------------------------

import type { JourneyBookingAggregate } from '../../domain/aggregates/journey-booking.aggregate';

// -----------------------------------------------------------------------------
// Entity
// -----------------------------------------------------------------------------

import { JourneyBookingPricingEntity } from '../../domain/entities/journey-booking-pricing.entity';

// -----------------------------------------------------------------------------
// Exceptions
// -----------------------------------------------------------------------------

import { JourneyBookingNotFoundException } from '../../domain/exceptions';

// -----------------------------------------------------------------------------
// Repository
// -----------------------------------------------------------------------------

import type { JourneyBookingRepository } from '../../domain/repositories/journey-booking.repository';

// -----------------------------------------------------------------------------
// Dependency Injection Tokens
// -----------------------------------------------------------------------------

import { JOURNEY_BOOKING_TOKENS } from '../journey-booking.tokens';

// -----------------------------------------------------------------------------
// Handler
// -----------------------------------------------------------------------------

/**
 * Handles creation and attachment of the pricing snapshot for an existing
 * Journey Booking.
 *
 * The handler is an application-layer orchestrator.
 *
 * It does NOT:
 *
 * - implement pricing business rules;
 * - mutate aggregate state directly;
 * - recreate aggregate invariants;
 * - contain persistence logic;
 * - communicate directly with infrastructure.
 *
 * Those responsibilities remain within their respective boundaries.
 *
 * The workflow is:
 *
 *     SetJourneyBookingPricingCommand
 *                    ↓
 *     JourneyBookingRepository
 *                    ↓
 *     JourneyBookingAggregate
 *                    ↓
 *     JourneyBookingPricingEntity.create()
 *                    ↓
 *     aggregate.attachPricing()
 *                    ↓
 *     JourneyBookingRepository.save()
 *
 * The repository is resolved through:
 *
 *     JOURNEY_BOOKING_TOKENS.REPOSITORY
 */
@Injectable()
export class SetJourneyBookingPricingHandler implements CommandHandler<
  SetJourneyBookingPricingCommand,
  JourneyBookingAggregate
> {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  constructor(
    @Inject(JOURNEY_BOOKING_TOKENS.REPOSITORY)
    private readonly repository: JourneyBookingRepository,
  ) {}

  // ===========================================================================
  // Execute
  // ===========================================================================

  public async execute(
    command: SetJourneyBookingPricingCommand,
  ): Promise<JourneyBookingAggregate> {
    // -------------------------------------------------------------------------
    // Load Aggregate
    // -------------------------------------------------------------------------

    const aggregate = await this.repository.findByPublicId(
      command.journeyBookingPublicId,
    );

    // -------------------------------------------------------------------------
    // Not Found
    // -------------------------------------------------------------------------

    if (aggregate === null) {
      throw new JourneyBookingNotFoundException(
        command.journeyBookingPublicId.value,
      );
    }

    // -------------------------------------------------------------------------
    // Create Pricing
    // -------------------------------------------------------------------------
    //
    // The pricing entity generates its own public identity.
    //
    // Discount and adjustment default to zero inside the entity factory when
    // they are not supplied.
    //

    const pricing = JourneyBookingPricingEntity.create({
      pricePerSeat: command.pricePerSeat,

      seats: command.seats,

      subtotal: command.subtotal,

      discountAmount: command.discountAmount,

      adjustmentAmount: command.adjustmentAmount,

      totalAmount: command.totalAmount,

      currency: command.currency,
    });

    // -------------------------------------------------------------------------
    // Attach Pricing
    // -------------------------------------------------------------------------
    //
    // The aggregate requires correlation metadata because attaching pricing
    // records a JourneyBookingPricingSetEvent.
    //

    aggregate.attachPricing(
      pricing,
      command.correlationId,
      command.causationId,
    );

    // -------------------------------------------------------------------------
    // Persistence
    // -------------------------------------------------------------------------

    await this.repository.save(aggregate);

    // -------------------------------------------------------------------------
    // Result
    // -------------------------------------------------------------------------

    return aggregate;
  }
}
