// -----------------------------------------------------------------------------
// Authentication — Authenticate Request DTO
// -----------------------------------------------------------------------------
//
// REST request DTO for authenticating a SisiMove user.
//
// Public login contract:
//
//     emailOrPhoneNumber + password
//
// Example:
//
//     {
//       "emailOrPhoneNumber": "ramah@example.com",
//       "password": "sisimove123"
//     }
//
// Or:
//
//     {
//       "emailOrPhoneNumber": "+254706439548",
//       "password": "sisimove123"
//     }
//
// -----------------------------------------------------------------------------
//
// Authentication workflow:
//
//     Authenticate Request
//             │
//             ├── emailOrPhoneNumber
//             │
//             └── password
//                    │
//                    ▼
//              Application Handler
//                    │
//                    ▼
//                 Identity
//                    │
//                    │ identityPublicId
//                    ▼
//              Authentication
//                    │
//                    ▼
//             Password verification
//                    │
//             ┌──────┴──────┐
//             │             │
//           Failure       Success
//             │             │
//             ▼             ▼
//        record failure  record success
//                           │
//                           ▼
//                         Session
//
// The client does NOT provide AuthenticationPublicId.
//
// AuthenticationPublicId is an internal aggregate identifier. The application
// workflow resolves Authentication from the Identity identified by the supplied
// email address or phone number.
//
// -----------------------------------------------------------------------------
//
// This DTO contains transport-level primitive values only.
//
// The DTO intentionally does NOT import or depend on:
//
// - Authentication domain value objects;
// - Identity domain value objects;
// - Authentication aggregates;
// - Identity aggregates;
// - application commands;
// - domain events;
// - persistence models.
//
// DTO-to-command conversion belongs at the presentation/application boundary.
//
// -----------------------------------------------------------------------------
//
// Input ownership:
//
// The client owns:
//
// - emailOrPhoneNumber;
// - password.
//
// The application boundary owns:
//
// - correlationId;
// - causationId;
// - AuthenticationPublicId;
// - IdentityPublicId.
//
// Therefore:
//
// - correlationId is generated by the controller/application boundary;
// - causationId is not supplied by a normal direct HTTP login request;
// - AuthenticationPublicId is resolved internally;
// - IdentityPublicId is resolved internally.
//
// -----------------------------------------------------------------------------
//
// Security:
//
// The password is transient credential input.
//
// It MUST NOT:
//
// - be logged;
// - be persisted;
// - be included in domain events;
// - be included in exceptions;
// - be stored on AuthenticationEntity.
//
// Password hashing and credential comparison belong to authentication
// infrastructure.
//
// This DTO performs only transport-level validation. It does not:
//
// - verify credentials;
// - hash passwords;
// - compare passwords;
// - determine whether authentication is permitted;
// - determine lock thresholds;
// - lock Authentication;
// - unlock Authentication;
// - modify authentication state;
// - create a Session;
// - generate access tokens;
// - generate refresh tokens;
// - create a Device;
// - revoke Sessions;
// - validate Identity domain state;
// - send notifications;
// - perform external side effects.
//
// -----------------------------------------------------------------------------
//
// Validation:
//
// The DTO validates only that:
//
// - emailOrPhoneNumber is a non-empty string;
// - emailOrPhoneNumber does not exceed the transport limit;
// - password is a non-empty string;
// - password does not exceed the transport limit.
//
// Authentication-specific credential policy belongs to the appropriate
// application/security policy and infrastructure.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS Swagger
// -----------------------------------------------------------------------------

import { ApiProperty } from '@nestjs/swagger';

// -----------------------------------------------------------------------------
// Class Transformer
// -----------------------------------------------------------------------------

import { Transform, type TransformFnParams } from 'class-transformer';

// -----------------------------------------------------------------------------
// Class Validator
// -----------------------------------------------------------------------------

import { IsNotEmpty, IsString, MaxLength, MinLength } from 'class-validator';

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/**
 * Trims surrounding whitespace from string transport values.
 *
 * This is appropriate for the login identifier because accidental leading
 * or trailing whitespace should not cause an otherwise valid identifier to
 * fail authentication.
 *
 * The password is intentionally NOT transformed.
 *
 * Passwords must be treated as exact credentials. Whitespace may be a
 * legitimate part of a password and therefore must never be silently
 * removed or modified by the DTO.
 */
const trimString = ({ value }: TransformFnParams): unknown =>
  typeof value === 'string' ? value.trim() : value;

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------
//
// These are transport-level validation constraints.
//
// They do not define the complete authentication password policy.
//

const MIN_EMAIL_OR_PHONE_NUMBER_LENGTH = 1;
const MAX_EMAIL_OR_PHONE_NUMBER_LENGTH = 254;

const MIN_PASSWORD_LENGTH = 1;
const MAX_PASSWORD_LENGTH = 128;

// -----------------------------------------------------------------------------
// DTO
// -----------------------------------------------------------------------------

/**
 * REST request for authenticating a SisiMove user.
 *
 * Required transport input:
 *
 * - emailOrPhoneNumber;
 * - password.
 *
 * No internal aggregate identifiers or correlation metadata are accepted
 * from the client.
 *
 * The presentation layer converts this DTO into:
 *
 *     AuthenticateAuthenticationCommand
 *
 * using:
 *
 *     emailOrPhoneNumber
 *     password
 *     generated correlationId
 *
 * Authentication and Identity public identifiers are resolved internally by
 * the application workflow.
 */
export class AuthenticateRequestDto {
  // ===========================================================================
  // Email / Phone Number
  // ===========================================================================

  /**
   * User-facing login identifier.
   *
   * Accepts either:
   *
   * - an email address;
   * - a phone number.
   *
   * The application workflow determines which identifier was supplied and
   * resolves the corresponding Identity.
   *
   * This remains a primitive string at the REST boundary.
   *
   * Example:
   *
   *     ramah@example.com
   *
   * or:
   *
   *     +254706439548
   */
  @ApiProperty({
    example: 'ramah@example.com',
    description:
      'Email address or phone number used to identify the user for authentication.',
    minLength: MIN_EMAIL_OR_PHONE_NUMBER_LENGTH,
    maxLength: MAX_EMAIL_OR_PHONE_NUMBER_LENGTH,
  })
  @Transform(trimString)
  @IsString({
    message: 'emailOrPhoneNumber must be a string.',
  })
  @IsNotEmpty({
    message: 'emailOrPhoneNumber must not be empty.',
  })
  @MinLength(MIN_EMAIL_OR_PHONE_NUMBER_LENGTH, {
    message: 'emailOrPhoneNumber must not be empty.',
  })
  @MaxLength(MAX_EMAIL_OR_PHONE_NUMBER_LENGTH, {
    message: `emailOrPhoneNumber must not exceed ${MAX_EMAIL_OR_PHONE_NUMBER_LENGTH} characters.`,
  })
  emailOrPhoneNumber!: string;

  // ===========================================================================
  // Password
  // ===========================================================================

  /**
   * Transient plaintext password supplied for authentication.
   *
   * The password is passed unchanged through the authentication workflow and
   * compared against the stored Authentication password hash by the
   * PasswordHasher infrastructure service.
   *
   * IMPORTANT:
   *
   * The password is intentionally NOT transformed.
   *
   * In particular, surrounding whitespace is not trimmed because the password
   * must be treated as an exact credential.
   *
   * This value must never be:
   *
   * - persisted;
   * - logged;
   * - published in a domain event;
   * - stored on AuthenticationEntity;
   * - included in an exception message.
   *
   * Swagger marks this field as write-only so it represents request input and
   * is not treated as a response property.
   *
   * Example:
   *
   *     correct-horse-battery-staple
   */
  @ApiProperty({
    example: 'correct-horse-battery-staple',
    description:
      'Transient plaintext password supplied for authentication. It is never persisted, logged, or included in domain events.',
    minLength: MIN_PASSWORD_LENGTH,
    maxLength: MAX_PASSWORD_LENGTH,
    writeOnly: true,
  })
  @IsString({
    message: 'password must be a string.',
  })
  @IsNotEmpty({
    message: 'password must not be empty.',
  })
  @MinLength(MIN_PASSWORD_LENGTH, {
    message: 'password must not be empty.',
  })
  @MaxLength(MAX_PASSWORD_LENGTH, {
    message: `password must not exceed ${MAX_PASSWORD_LENGTH} characters.`,
  })
  password!: string;
}

// -----------------------------------------------------------------------------
// Exported Constants
// -----------------------------------------------------------------------------

export {
  MIN_EMAIL_OR_PHONE_NUMBER_LENGTH as AUTHENTICATION_EMAIL_OR_PHONE_MIN_LENGTH,
  MAX_EMAIL_OR_PHONE_NUMBER_LENGTH as AUTHENTICATION_EMAIL_OR_PHONE_MAX_LENGTH,
  MIN_PASSWORD_LENGTH as AUTHENTICATION_PASSWORD_MIN_LENGTH,
  MAX_PASSWORD_LENGTH as AUTHENTICATION_PASSWORD_MAX_LENGTH,
};
