// -----------------------------------------------------------------------------
// Identity — Create Permission Command
// -----------------------------------------------------------------------------
//
// Application command for creating a Permission aggregate.
//
// The command represents the intent to create a new Permission within the
// Identity / Authorization domain.
//
// The command does NOT:
//
// - construct PermissionEntity;
// - construct PermissionAggregate;
// - persist the Permission;
// - access Prisma;
// - assign the Permission to a Role;
// - create RolePermission relationships;
// - evaluate authorization;
// - emit PermissionCreatedEvent directly;
// - communicate with external systems.
//
// The application handler is responsible for:
//
// 1. validating/resolving the command inputs;
// 2. constructing the PermissionEntity;
// 3. creating the PermissionAggregate;
// 4. recording PermissionCreatedEvent through the aggregate;
// 5. persisting the aggregate.
//
// The aggregate remains responsible for its own domain behavior and state.
//
// -----------------------------------------------------------------------------
//
// Creation:
//
// Command
//   │
//   ▼
// PermissionEntity.create(...)
//   │
//   ▼
// PermissionAggregate.create(...)
//   │
//   ▼
// PermissionAggregate.recordCreated(...)
//   │
//   ▼
// PermissionCreatedEvent
//
// -----------------------------------------------------------------------------
//
// Permission identity:
//
// - publicId is generated by the domain/entity factory.
// - code is the stable machine-readable Permission identifier.
// - resource identifies the protected resource.
// - action identifies the authorized action.
//
// The command therefore does NOT accept a PermissionPublicId.
//
// -----------------------------------------------------------------------------
//
// Uniqueness:
//
// The aggregate can validate that the Permission itself is structurally
// consistent, but uniqueness of:
//
//     Permission.code
//     Permission(resource, action)
//
// is a repository/database/application boundary concern.
//
// The command does not perform persistence-level uniqueness checks.
//
// -----------------------------------------------------------------------------
//
// System Permissions:
//
// isSystem indicates whether the Permission is system-managed.
//
// The command may request creation of a system Permission, but authorization
// to create system-level Permissions belongs to the application/security
// boundary and is not encoded in this command.
//
// -----------------------------------------------------------------------------
//
// Correlation / causation:
//
// correlationId is required and MUST appear before optional parameters.
//
// causationId is optional and identifies the command/event that caused this
// creation operation.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import type { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Value Objects
// -----------------------------------------------------------------------------

import type { PermissionCode } from '../../domain/value-objects/permission-code.vo';

import type { PermissionResource } from '../../domain/value-objects/permission-resource.vo';

import type { PermissionAction } from '../../domain/value-objects/permission-action.vo';

// =============================================================================
// Command
// =============================================================================

/**
 * Application command for creating a Permission.
 *
 * The command carries business inputs required by the application layer to
 * construct a new Permission aggregate.
 *
 * The Permission public identifier is intentionally omitted because it is
 * generated by the domain/entity creation process.
 */
export class CreatePermissionCommand implements Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    /**
     * Human-readable name of the Permission.
     *
     * This value is passed to the PermissionEntity factory where the domain
     * validates and normalizes it.
     */
    public readonly name: string,

    /**
     * Stable machine-readable Permission code.
     *
     * The code uniquely identifies the Permission at the authorization
     * boundary.
     */
    public readonly code: PermissionCode,

    /**
     * Resource protected by the Permission.
     */
    public readonly resource: PermissionResource,

    /**
     * Action authorized by the Permission.
     */
    public readonly action: PermissionAction,

    /**
     * Optional human-readable Permission description.
     */
    public readonly description: string | undefined,

    /**
     * Indicates whether this is a system-managed Permission.
     *
     * Defaults to false for application/custom Permissions.
     */
    public readonly isSystem: boolean,

    /**
     * Initial lifecycle state of the Permission.
     *
     * The Permission creation factory is responsible for establishing the
     * domain-valid initial state.
     */
    public readonly isActive: boolean,

    /**
     * Correlation identifier for the command and resulting domain event.
     *
     * This parameter is required and therefore intentionally appears before
     * the optional causationId parameter.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command, event, or operation that caused
     * this Permission creation request.
     */
    public readonly causationId?: string,
  ) {}
}
