// src/domains/assets/domain/value-objects/asset-category.enum.ts

export enum AssetCategory {
  PROFILE_PHOTO = 'PROFILE_PHOTO',
  COVER_PHOTO = 'COVER_PHOTO',
  AVATAR = 'AVATAR',

  GOVERNMENT_ID = 'GOVERNMENT_ID',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  PASSPORT = 'PASSPORT',
  SELFIE = 'SELFIE',

  POST_MEDIA = 'POST_MEDIA',
  COMMENT_MEDIA = 'COMMENT_MEDIA',
  STORY_MEDIA = 'STORY_MEDIA',
  REEL_MEDIA = 'REEL_MEDIA',

  CHAT_ATTACHMENT = 'CHAT_ATTACHMENT',

  TRIP_MEDIA = 'TRIP_MEDIA',
  DESTINATION_MEDIA = 'DESTINATION_MEDIA',

  VEHICLE_PHOTO = 'VEHICLE_PHOTO',

  ORGANIZATION_LOGO = 'ORGANIZATION_LOGO',
  ORGANIZATION_BANNER = 'ORGANIZATION_BANNER',

  PRODUCT_MEDIA = 'PRODUCT_MEDIA',

  EVENT_BANNER = 'EVENT_BANNER',

  OTHER = 'OTHER',
}
