export enum AssetVariantType {
  ORIGINAL = 'ORIGINAL',
  ICON = 'ICON',
  THUMBNAIL = 'THUMBNAIL',
  TINY = 'TINY',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  XLARGE = 'XLARGE',
  WEB = 'WEB',
  WEBP = 'WEBP',
  AVIF = 'AVIF',
  PREVIEW = 'PREVIEW',
  COMPRESSED = 'COMPRESSED',
  HD = 'HD',
  FULL_HD = 'FULL_HD',
  QHD = 'QHD',
  UHD_4K = 'UHD_4K',
}
