export enum AssetReferenceField {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  AVATAR = 'AVATAR',
  COVER = 'COVER',
  BANNER = 'BANNER',
  THUMBNAIL = 'THUMBNAIL',
  PREVIEW = 'PREVIEW',
  GALLERY = 'GALLERY',
  ATTACHMENT = 'ATTACHMENT',
  DOCUMENT = 'DOCUMENT',
  OTHER = 'OTHER',
}
