// -----------------------------------------------------------------------------
// sisiMove — Create Journey Schema
// -----------------------------------------------------------------------------
//
// Creates the Journey aggregate.
//
// The provider identity is derived from the authenticated session on the
// backend. The frontend MUST NOT supply providerPublicId.
//
// Journey components are configured after aggregate creation through their
// dedicated Journey APIs.
//
// The frontend supplies only the idempotency key required to make the creation
// command safe across retries and React remounts.
//
// `idempotencyKey` is request/application metadata. It is NOT a Journey
// aggregate field and must not be persisted as Journey business data.
//
// Backend responsibilities:
// - derive the authenticated provider from the current session;
// - validate the idempotency key;
// - enforce idempotent creation;
// - create the Journey aggregate;
// - return the existing Journey when the same idempotency key is replayed.
//
// -----------------------------------------------------------------------------
//
// Example request:
//
//     {
//       "idempotencyKey": "550e8400-e29b-41d4-a716-446655440000"
//     }
//
// -----------------------------------------------------------------------------
//
// This schema intentionally accepts no client-controlled Journey fields.
//
// -----------------------------------------------------------------------------

import { z } from 'zod';

// -----------------------------------------------------------------------------
// Schema
// -----------------------------------------------------------------------------

export const createJourneySchema = z.strictObject({
  /**
   * Stable identifier for one Journey creation attempt.
   *
   * This value is generated by the authenticated frontend and reused when
   * the creation request is retried or the creation entry component remounts.
   *
   * The backend is authoritative for idempotency.
   */
  idempotencyKey: z.string().min(1),
});

// -----------------------------------------------------------------------------
// Input
// -----------------------------------------------------------------------------

export type CreateJourneyInput = z.infer<
  typeof createJourneySchema
>;

