// -----------------------------------------------------------------------------
// Financial Settlement — Create Command
// -----------------------------------------------------------------------------
//
// Application command for creating a Financial Settlement aggregate.
//
// The command carries domain-ready value objects rather than raw transport
// values.
//
// DTO-to-domain conversion belongs to the presentation/application boundary.
//
// A newly created Financial Settlement consists of:
//
// FinancialSettlementAggregate
// └── FinancialSettlementEntity
//     └── FinancialSettlementItemEntity[]
//         └── FinancialSettlementAllocationEntity[]
//
// Settlement Items are intentionally NOT created by this command.
// They are added through the Settlement aggregate after creation and while
// the Settlement remains PENDING.
//
// A newly created Financial Settlement is expected to:
//
// - have PENDING lifecycle status;
// - have a zero total amount;
// - contain no Settlement Items;
// - be single-currency.
//
// The initial lifecycle status and total amount are determined by the domain
// creation policy and are therefore intentionally NOT supplied by this
// command.
//
// This command does NOT:
//
// - Begin settlement processing.
// - Create Settlement Items.
// - Allocate settlement amounts.
// - Create Financial Transactions.
// - Execute Financial Transactions.
// - Modify Financial Account balances.
// - Execute disbursements.
// - Perform accounting.
// - Communicate with external financial providers.
//
// Those responsibilities belong to the respective settlement application,
// transaction, account, integration, disbursement, and accounting boundaries.
//
// Correlation and causation identifiers are carried for application-level
// tracing and domain-event correlation.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import type { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Domain Value Objects
// -----------------------------------------------------------------------------

import type { Currency } from '../../domain/value-objects';

// -----------------------------------------------------------------------------
// Command
// -----------------------------------------------------------------------------

/**
 * Command for creating a Financial Settlement aggregate.
 *
 * The command represents the intent to create an empty Financial Settlement
 * batch in a single currency.
 *
 * Required domain input:
 *
 * - currency
 *
 * The following values are intentionally NOT supplied:
 *
 * - settlement status — determined by the domain creation policy;
 * - total amount — starts at zero;
 * - settlement items — added after aggregate creation;
 * - settlement allocations — created during settlement processing;
 * - settlement public ID — generated by the domain/entity creation policy.
 *
 * Creation itself does not begin settlement processing.
 */
export class CreateFinancialSettlementCommand implements Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  constructor(
    /**
     * Currency of the Financial Settlement.
     *
     * A Financial Settlement is intentionally single-currency.
     *
     * Settlement Items added later must use the same currency.
     */
    public readonly currency: Currency,

    /**
     * Correlation identifier for the command and resulting domain events.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or operation that caused this
     * command.
     */
    public readonly causationId?: string,
  ) {}
}
