// -----------------------------------------------------------------------------
// Financial Settlement — Process Command Handler
// -----------------------------------------------------------------------------
//
// Application command handler responsible for starting processing of an
// existing Financial Settlement aggregate.
//
// Responsibilities:
//
// - Resolve the Financial Settlement aggregate.
// - Ensure the Settlement exists.
// - Delegate the PENDING → PROCESSING lifecycle transition to the aggregate.
// - Persist the modified aggregate.
//
// The FinancialSettlementAggregate remains authoritative for:
//
// - lifecycle validation;
// - requiring at least one Settlement Item;
// - processing transition;
// - aggregate invariants;
// - processing timestamp;
// - domain event creation.
//
// This handler does NOT:
//
// - Create Settlement Items.
// - Allocate Settlement Items.
// - Create Settlement Allocations.
// - Create Financial Transactions.
// - Execute Financial Transactions.
// - Modify Financial Account balances.
// - Execute disbursements.
// - Perform accounting.
// - Communicate with external settlement/payment providers.
// - Move money.
//
// External settlement execution belongs to the appropriate application and
// integration boundaries.
//
// Financial movement belongs to Financial Transactions and the appropriate
// Financial Account workflows.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// NestJS
// -----------------------------------------------------------------------------

import { Inject, Injectable } from '@nestjs/common';

// -----------------------------------------------------------------------------
// Application — Tokens
// -----------------------------------------------------------------------------

import { FINANCIAL_SETTLEMENT_TOKENS } from '../financial-settlement.tokens';

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import type { CommandHandler } from '../../../../foundation/kernel/application/command-handler';

// -----------------------------------------------------------------------------
// Command
// -----------------------------------------------------------------------------

import type { ProcessFinancialSettlementCommand } from '../commands/process-financial-settlement.command';

// -----------------------------------------------------------------------------
// Aggregate
// -----------------------------------------------------------------------------

import type { FinancialSettlementAggregate } from '../../domain/aggregates/financial-settlement.aggregate';

// -----------------------------------------------------------------------------
// Repository
// -----------------------------------------------------------------------------

import type { FinancialSettlementRepository } from '../../domain/repositories/financial-settlement.repository';

// -----------------------------------------------------------------------------
// Exceptions
// -----------------------------------------------------------------------------

import { FinancialSettlementNotFoundException } from '../../domain/exceptions';

// -----------------------------------------------------------------------------
// Handler
// -----------------------------------------------------------------------------

/**
 * Starts processing of an existing Financial Settlement.
 *
 * Lifecycle transition:
 *
 *     PENDING → PROCESSING
 *
 * The FinancialSettlementAggregate remains the sole authority for deciding
 * whether the transition is valid.
 *
 * A Financial Settlement must contain at least one Settlement Item before
 * processing can begin.
 *
 * The processing timestamp is generated by the aggregate itself.
 *
 * Application orchestration:
 *
 *     ProcessFinancialSettlementCommand
 *                    │
 *                    ▼
 *     FinancialSettlementRepository
 *                    │
 *                    ▼
 *     FinancialSettlementAggregate
 *                    │
 *                    ├── startProcessing()
 *                    │
 *                    └── FinancialSettlementProcessingEvent
 *                    │
 *                    ▼
 *     FinancialSettlementRepository.save()
 *
 * No financial movement occurs in this handler.
 */
@Injectable()
export class ProcessFinancialSettlementHandler implements CommandHandler<
  ProcessFinancialSettlementCommand,
  FinancialSettlementAggregate
> {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    @Inject(FINANCIAL_SETTLEMENT_TOKENS.REPOSITORY)
    private readonly repository: FinancialSettlementRepository,
  ) {}

  // ===========================================================================
  // Execute
  // ===========================================================================

  public async execute(
    command: ProcessFinancialSettlementCommand,
  ): Promise<FinancialSettlementAggregate> {
    // -------------------------------------------------------------------------
    // 1. Resolve Financial Settlement
    // -------------------------------------------------------------------------
    //
    // The command carries the public Settlement identity.
    //
    // The repository returns the complete aggregate:
    //
    // FinancialSettlementAggregate
    // └── FinancialSettlementEntity
    //     └── FinancialSettlementItemEntity[]
    //         └── FinancialSettlementAllocationEntity[]
    //
    // Settlement Items remain internal entities owned by the aggregate.
    // -------------------------------------------------------------------------

    const aggregate = await this.repository.findByPublicId(
      command.settlementPublicId,
    );

    // -------------------------------------------------------------------------
    // 2. Ensure Financial Settlement Exists
    // -------------------------------------------------------------------------

    if (aggregate === null) {
      throw new FinancialSettlementNotFoundException(
        `Financial Settlement "${command.settlementPublicId.value}" was not found.`,
      );
    }

    // -------------------------------------------------------------------------
    // 3. Start Processing
    // -------------------------------------------------------------------------
    //
    // The aggregate owns the complete processing transition.
    //
    // It validates:
    //
    // - current status is PENDING;
    // - at least one Settlement Item exists;
    // - processing timestamp is valid.
    //
    // The aggregate generates the processing timestamp through its default:
    //
    //     at = new Date()
    //
    // It then performs:
    //
    //     PENDING → PROCESSING
    //
    // and records:
    //
    //     FinancialSettlementProcessingEvent
    //
    // The handler intentionally does not duplicate these domain rules.
    // -------------------------------------------------------------------------

    aggregate.startProcessing(
      new Date(),
      command.correlationId,
      command.causationId,
    );

    // -------------------------------------------------------------------------
    // 4. Persist Aggregate
    // -------------------------------------------------------------------------
    //
    // Persistence remains the responsibility of the repository.
    //
    // The repository persists the complete Financial Settlement aggregate
    // graph and participates in the application's domain-event publication
    // strategy.
    // -------------------------------------------------------------------------

    await this.repository.save(aggregate);

    // -------------------------------------------------------------------------
    // 5. Return Aggregate
    // -------------------------------------------------------------------------

    return aggregate;
  }
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default ProcessFinancialSettlementHandler;
