// src/features/journey/api/journeys/cancel-journey.ts

// -----------------------------------------------------------------------------
// sisiMove — Cancel Journey API
// -----------------------------------------------------------------------------
//
// Mirrors:
//
//   POST /journeys/:journeyPublicId/cancel
//
// The application handler confirms:
//
// - journeyPublicId is supplied through the HTTP route;
// - reason is supplied by the caller;
// - correlationId is generated by the backend/controller;
// - causationId is not supplied by the HTTP client;
// - cancelledAt is optional;
// - when cancelledAt is omitted, the application handler uses `new Date()`;
// - the command handler returns void;
// - the Journey aggregate owns the cancellation transition and its business
//   invariants.
//
// Therefore the frontend sends only:
//
//   - reason
//   - optional cancelledAt
//
// The frontend must not determine whether the Journey is cancellable.
// -----------------------------------------------------------------------------

import { authenticatedApiClient } from "@/features/authentication/http/authenticated-api-client";
import type { RequestOptions } from "@/foundation/http";

/**
 * HTTP input accepted when cancelling a Journey.
 *
 * `reason` is required because the backend passes it directly into
 * Journey.cancel(...).
 *
 * `cancelledAt` remains an HTTP string because the backend controller is
 * responsible for converting it into a Date.
 */
export interface CancelJourneyRequest {
  readonly reason: string;
  readonly cancelledAt?: string;
}

/**
 * Cancels an existing Journey.
 *
 * Backend:
 *   POST /journeys/:journeyPublicId/cancel
 *
 * Request body:
 *   {
 *     reason: string;
 *     cancelledAt?: string;
 *   }
 *
 * Backend-generated values:
 *   - correlationId
 *   - default cancelledAt when omitted
 *
 * Response:
 *   no response body
 *
 * The resulting Journey state must be obtained from the canonical
 * authenticated Journey query rather than fabricated locally.
 */
export async function cancelJourney(
  journeyPublicId: string,
  request: CancelJourneyRequest,
  options: RequestOptions = {},
): Promise<void> {
  await authenticatedApiClient.post<void>(
    `/journeys/${encodeURIComponent(journeyPublicId)}/cancel`,
    request,
    options,
  );
}