// src/features/journey/api/journeys/complete-journey.ts

// -----------------------------------------------------------------------------
// sisiMove — Complete Journey API
// -----------------------------------------------------------------------------
//
// Mirrors:
//
//   POST /journeys/:journeyPublicId/complete
//
// The application handler confirms:
//
// - journeyPublicId is supplied through the HTTP route;
// - correlationId is generated by the backend/controller;
// - causationId is not supplied by the HTTP client;
// - completedAt is optional;
// - when completedAt is omitted, the application handler uses `new Date()`;
// - the command handler returns void;
// - the Journey aggregate owns the completion transition and its business
//   invariants.
//
// Therefore the frontend sends only the optional HTTP-level completedAt value.
// -----------------------------------------------------------------------------

import { authenticatedApiClient } from "@/features/authentication/http/authenticated-api-client";
import type { RequestOptions } from "@/foundation/http";

/**
 * Optional HTTP input accepted when completing a Journey.
 *
 * The frontend uses the HTTP representation (`string`).
 * The backend controller converts this value into a Date before constructing
 * CompleteJourneyCommand.
 */
export interface CompleteJourneyRequest {
  readonly completedAt?: string;
}

/**
 * Completes an existing Journey.
 *
 * Backend:
 *   POST /journeys/:journeyPublicId/complete
 *
 * Request body:
 *   {
 *     completedAt?: string;
 *   }
 *
 * Backend-generated values:
 *   - correlationId
 *   - default completedAt when omitted
 *
 * Response:
 *   no response body
 *
 * The resulting Journey state must be obtained from the canonical
 * authenticated Journey query rather than constructed locally.
 */
export async function completeJourney(
  journeyPublicId: string,
  request: CompleteJourneyRequest = {},
  options: RequestOptions = {},
): Promise<void> {
  await authenticatedApiClient.post<void>(
    `/journeys/${encodeURIComponent(journeyPublicId)}/complete`,
    request,
    options,
  );
}