// src/features/journey/api/journeys/expire-journey.ts

// -----------------------------------------------------------------------------
// sisiMove — Expire Journey API
// -----------------------------------------------------------------------------
//
// Mirrors:
//
//   POST /journeys/:journeyPublicId/expire
//
// The application handler confirms:
//
// - journeyPublicId is supplied through the HTTP route;
// - correlationId is generated by the backend/controller;
// - causationId is not supplied by the HTTP client;
// - expiredAt is optional;
// - when expiredAt is omitted, the application handler uses `new Date()`;
// - the command handler returns void;
// - the Journey aggregate owns the expiration transition and its business
//   invariants.
//
// Therefore the frontend sends only the optional HTTP-level expiredAt value.
// -----------------------------------------------------------------------------

import { authenticatedApiClient } from "@/features/authentication/http/authenticated-api-client";
import type { RequestOptions } from "@/foundation/http";

/**
 * Optional HTTP input accepted when expiring a Journey.
 *
 * The frontend uses the HTTP representation (`string`).
 * The backend controller converts this value into a Date before constructing
 * ExpireJourneyCommand.
 */
export interface ExpireJourneyRequest {
  readonly expiredAt?: string;
}

/**
 * Expires an existing Journey.
 *
 * Backend:
 *   POST /journeys/:journeyPublicId/expire
 *
 * Request body:
 *   {
 *     expiredAt?: string;
 *   }
 *
 * Backend-generated values:
 *   - correlationId
 *   - default expiredAt when omitted
 *
 * Response:
 *   no response body
 *
 * The resulting Journey state must be obtained from the canonical
 * authenticated Journey query rather than fabricated locally.
 */
export async function expireJourney(
  journeyPublicId: string,
  request: ExpireJourneyRequest = {},
  options: RequestOptions = {},
): Promise<void> {
  await authenticatedApiClient.post<void>(
    `/journeys/${encodeURIComponent(journeyPublicId)}/expire`,
    request,
    options,
  );
}