// src/features/journey/api/journeys/publish-journey.ts

// -----------------------------------------------------------------------------
// sisiMove — Publish Journey API
// -----------------------------------------------------------------------------
//
// Mirrors:
//
//   POST /journeys/:journeyPublicId/publish
//
// The application handler confirms:
//
// - journeyPublicId is the only Journey identifier supplied by the HTTP route;
// - correlationId is generated by the backend/controller;
// - causationId is not supplied by the HTTP client;
// - publishedAt is optional;
// - when publishedAt is omitted, the application handler/domain receives
//   `new Date()`;
// - the command handler returns void;
// - the Journey aggregate owns the actual publication transition and
//   invariants.
//
// Therefore the frontend sends only the optional HTTP-level publishedAt value.
// -----------------------------------------------------------------------------

import { authenticatedApiClient } from "@/features/authentication/http/authenticated-api-client";
import type { RequestOptions } from "@/foundation/http";

/**
 * Optional HTTP input accepted when publishing a Journey.
 *
 * This intentionally uses the HTTP representation (`string`) rather than
 * JavaScript `Date`. The backend controller converts the supplied value into
 * a Date before constructing PublishJourneyCommand.
 */
export interface PublishJourneyRequest {
  readonly publishedAt?: string;
}

/**
 * Publishes an existing Journey.
 *
 * Backend:
 *   POST /journeys/:journeyPublicId/publish
 *
 * Request body:
 *   {
 *     publishedAt?: string;
 *   }
 *
 * Backend-generated values:
 *   - correlationId
 *   - default publishedAt when omitted
 *
 * Response:
 *   no response body
 *
 * The resulting Journey state must be obtained from the canonical
 * authenticated Journey query rather than constructed locally.
 */
export async function publishJourney(
  journeyPublicId: string,
  request: PublishJourneyRequest = {},
  options: RequestOptions = {},
): Promise<void> {
  await authenticatedApiClient.post<void>(
    `/journeys/${encodeURIComponent(journeyPublicId)}/publish`,
    request,
    options,
  );
}