// src/features/journey/api/journeys/start-journey.ts

// -----------------------------------------------------------------------------
// sisiMove — Start Journey API
// -----------------------------------------------------------------------------
//
// Mirrors:
//
//   POST /journeys/:journeyPublicId/start
//
// The application handler confirms:
//
// - journeyPublicId is supplied through the HTTP route;
// - correlationId is generated by the backend/controller;
// - causationId is not supplied by the HTTP client;
// - startedAt is optional;
// - when startedAt is omitted, the application handler uses `new Date()`;
// - the command handler returns void;
// - the Journey aggregate owns the actual start transition and its
//   business invariants.
//
// Therefore the frontend sends only the optional HTTP-level startedAt value.
// -----------------------------------------------------------------------------

import { authenticatedApiClient } from "@/features/authentication/http/authenticated-api-client";
import type { RequestOptions } from "@/foundation/http";

/**
 * Optional HTTP input accepted when starting a Journey.
 *
 * The frontend uses the HTTP representation (`string`).
 * The backend controller converts this value into a Date before constructing
 * StartJourneyCommand.
 */
export interface StartJourneyRequest {
  readonly startedAt?: string;
}

/**
 * Starts an existing Journey.
 *
 * Backend:
 *   POST /journeys/:journeyPublicId/start
 *
 * Request body:
 *   {
 *     startedAt?: string;
 *   }
 *
 * Backend-generated values:
 *   - correlationId
 *   - default startedAt when omitted
 *
 * Response:
 *   no response body
 *
 * The resulting Journey state must be obtained from the canonical
 * authenticated Journey query rather than constructed locally.
 */
export async function startJourney(
  journeyPublicId: string,
  request: StartJourneyRequest = {},
  options: RequestOptions = {},
): Promise<void> {
  await authenticatedApiClient.post<void>(
    `/journeys/${encodeURIComponent(journeyPublicId)}/start`,
    request,
    options,
  );
}