// -----------------------------------------------------------------------------
// Accounting — Create Accounting Account Command
// -----------------------------------------------------------------------------
//
// Application command for creating an Accounting Account aggregate.
//
// User-facing intent:
//
//     Create Accounting Account
//
// The command carries the domain data required to create the
// AccountingAccountEntity and AccountingAccountAggregate.
//
// This command does NOT:
//
// - create AccountingAccountEntity;
// - create AccountingAccountAggregate;
// - access Prisma;
// - access repositories;
// - enforce account lifecycle rules;
// - generate domain events;
// - persist the aggregate.
//
// Aggregate creation belongs to CreateAccountingAccountHandler.
//
// Domain invariants belong to AccountingAccountEntity / Aggregate.
//
// Persistence belongs to AccountingAccountRepository.
//
// -----------------------------------------------------------------------------
//
// Aggregate boundary:
//
//     AccountingAccountAggregate
//     └── AccountingAccountEntity
//
// The aggregate does not exist when this command begins.
//
// The AccountingAccountPublicId and internal entity identity are therefore
// intentionally NOT supplied.
//
// They are generated by AccountingAccountEntity.create().
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation — Application Command
// -----------------------------------------------------------------------------

import type { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Foundation — Identity
// -----------------------------------------------------------------------------

import type { UniqueEntityId } from '../../../../foundation/kernel/domain/unique-entity-id';

// -----------------------------------------------------------------------------
// Accounting — Domain Value Objects
// -----------------------------------------------------------------------------

import type { AccountingAccountCode } from '../../domain/value-objects/accounting-account-code.vo';

import type { AccountingAccountName } from '../../domain/value-objects/accounting-account-name.vo';

import type { AccountingAccountType } from '../../domain/value-objects/accounting-account-type.vo';

// =============================================================================
// Command
// =============================================================================

/**
 * Command for creating an Accounting Account.
 *
 * The Accounting Account aggregate does not exist when this command begins.
 *
 * The application handler is responsible for:
 *
 *     command
 *        ↓
 *     AccountingAccountEntity.create()
 *        ↓
 *     AccountingAccountAggregate.create()
 *        ↓
 *     aggregate.recordCreated()
 *        ↓
 *     repository.save()
 */
export class CreateAccountingAccountCommand implements Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    /**
     * Unique accounting code of the account.
     */
    public readonly code: AccountingAccountCode,

    /**
     * Human-readable accounting account name.
     */
    public readonly name: AccountingAccountName,

    /**
     * Classification of the accounting account.
     */
    public readonly type: AccountingAccountType,

    /**
     * Optional internal identity of the parent Accounting Account.
     *
     * The parent remains outside this aggregate's ownership boundary.
     *
     * The command carries only the opaque internal reference.
     */
    public readonly parentAccountId: UniqueEntityId | undefined = undefined,

    /**
     * Correlation identifier for the complete operation.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or domain event that caused
     * this operation.
     */
    public readonly causationId?: string,
  ) {}
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default CreateAccountingAccountCommand;
