// -----------------------------------------------------------------------------
// Accounting — Create Accounting Period Command
// -----------------------------------------------------------------------------
//
// Application command for creating an Accounting Period aggregate.
//
// User-facing intent:
//
//     Create Accounting Period
//
// The command carries the domain data required to create the
// AccountingPeriodEntity and AccountingPeriodAggregate.
//
// This command does NOT:
//
// - create AccountingPeriodEntity;
// - create AccountingPeriodAggregate;
// - access Prisma;
// - access repositories;
// - enforce period lifecycle rules;
// - determine period overlap;
// - generate domain events;
// - persist the aggregate.
//
// Aggregate creation belongs to CreateAccountingPeriodHandler.
//
// Domain invariants belong to AccountingPeriodEntity / Aggregate.
//
// Persistence belongs to AccountingPeriodRepository.
//
// -----------------------------------------------------------------------------
//
// Aggregate boundary:
//
//     AccountingPeriodAggregate
//     └── AccountingPeriodEntity
//
// The aggregate does not exist when this command begins.
//
// AccountingPeriodPublicId and internal entity identity are therefore
// intentionally NOT supplied.
//
// They are generated by AccountingPeriodEntity.create().
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation — Application Command
// -----------------------------------------------------------------------------

import type { Command } from '../../../../foundation/kernel/application/command';

// -----------------------------------------------------------------------------
// Accounting — Domain Value Objects
// -----------------------------------------------------------------------------

import type { AccountingPeriodName } from '../../domain/value-objects/accounting-period-name.vo';

// =============================================================================
// Command
// =============================================================================

/**
 * Command for creating an Accounting Period.
 *
 * The Accounting Period aggregate does not exist when this command begins.
 *
 * The application handler is responsible for:
 *
 *     command
 *        ↓
 *     AccountingPeriodEntity.create()
 *        ↓
 *     AccountingPeriodAggregate.create()
 *        ↓
 *     repository.save()
 */
export class CreateAccountingPeriodCommand implements Command {
  // ===========================================================================
  // Constructor
  // ===========================================================================

  public constructor(
    /**
     * Accounting Period name.
     */
    public readonly name: AccountingPeriodName,

    /**
     * Accounting Period start date.
     *
     * The entity enforces the period boundary invariant.
     */
    public readonly startsAt: Date,

    /**
     * Accounting Period end date.
     *
     * The entity enforces:
     *
     *     startsAt < endsAt
     */
    public readonly endsAt: Date,

    /**
     * Correlation identifier for the complete operation.
     */
    public readonly correlationId: string,

    /**
     * Optional identifier of the command or domain event that caused
     * this operation.
     */
    public readonly causationId?: string,
  ) {}
}

// -----------------------------------------------------------------------------
// Default Export
// -----------------------------------------------------------------------------

export default CreateAccountingPeriodCommand;
