// -----------------------------------------------------------------------------
// Commercial Earning Commission Repository
// -----------------------------------------------------------------------------
//
// Repository contract for the Commercial Earning Commission aggregate.
//
// Aggregate boundary:
//
//   CommercialEarningCommissionAggregate
//              │
//              └── CommercialEarningCommissionEntity
//
// The repository is responsible for:
//
// - persisting the Earning Commission aggregate;
// - removing the aggregate where permitted;
// - rehydrating the aggregate;
// - locating all Earning Commission aggregates;
// - locating commissions by public identity;
// - locating the commission associated with a Settlement;
// - locating commissions associated with a Journey;
// - locating commissions associated with a Provider;
// - locating commissions produced from a Commercial Commission Rule;
// - supporting lifecycle/status queries;
// - supporting existence checks.
//
// The repository belongs to the Commercial domain layer.
//
// Infrastructure concerns are intentionally excluded:
//
// - no Prisma;
// - no SQL;
// - no ORM models;
// - no database client;
// - no persistence DTOs.
//
// Infrastructure implementations are responsible for mapping persistence
// records to and from the Commercial Earning Commission aggregate.
//
// Commercial Earning Commission does NOT own:
//
// - Journey;
// - Journey Settlement;
// - Identity / Provider;
// - Commercial Commission Rule;
// - Wallet;
// - Treasury;
// - Accounting.
//
// These concepts are represented through public identifiers because they
// belong to other bounded contexts or independent Commercial aggregates.
//
// Historical commission values are snapshots on the Earning Commission entity:
//
// - commissionRulePublicId;
// - percentage;
// - baseAmount;
// - commissionAmount;
// - netAmount;
// - currency.
//
// Therefore, changes to future Commercial Commission Rules must not alter
// previously created earning commission assessments.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Aggregate
// -----------------------------------------------------------------------------

import type { CommercialEarningCommissionAggregate } from '../aggregates/commercial-earning-commission.aggregate';

// -----------------------------------------------------------------------------
// Entity
// -----------------------------------------------------------------------------

import type { CommercialEarningCommissionEntity } from '../entities/commercial-earning-commission.entity';

// -----------------------------------------------------------------------------
// Value Objects
// -----------------------------------------------------------------------------

import type { CommercialCommissionRulePublicId } from '../value-objects/commercial-commission-rule-public-id.vo';

import type { CommercialEarningCommissionJourneyPublicId } from '../value-objects/commercial-earning-commission-journey-public-id.vo';

import type { CommercialEarningCommissionProviderPublicId } from '../value-objects/commercial-earning-commission-provider-public-id.vo';

import type { CommercialEarningCommissionPublicId } from '../value-objects/commercial-earning-commission-public-id.vo';

import type { CommercialEarningCommissionSettlementPublicId } from '../value-objects/commercial-earning-commission-settlement-public-id.vo';

import type { CommercialEarningCommissionStatus } from '../value-objects/commercial-earning-commission-status.vo';

// -----------------------------------------------------------------------------
// Repository
// -----------------------------------------------------------------------------

/**
 * Repository contract for the Commercial Earning Commission aggregate.
 *
 * A Commercial Earning Commission is an independent Commercial aggregate root.
 *
 * The aggregate represents the platform commission retained from a provider's
 * earning generated by a Journey Settlement.
 */
export interface CommercialEarningCommissionRepository {
  // ---------------------------------------------------------------------------
  // Persistence
  // ---------------------------------------------------------------------------

  /**
   * Persists a Commercial Earning Commission aggregate.
   *
   * The implementation must persist the complete aggregate state represented
   * by the owned CommercialEarningCommissionEntity.
   */
  save(aggregate: CommercialEarningCommissionAggregate): Promise<void>;

  /**
   * Removes a Commercial Earning Commission aggregate.
   *
   * Deletion policy is determined by the application and infrastructure
   * layers.
   */
  delete(aggregate: CommercialEarningCommissionAggregate): Promise<void>;

  // ---------------------------------------------------------------------------
  // Aggregate Queries
  // ---------------------------------------------------------------------------

  /**
   * Finds all Commercial Earning Commission aggregates.
   *
   * Implementations should return results in a deterministic order.
   *
   * The recommended default ordering is createdAt descending so that the most
   * recently created commissions are returned first.
   */
  findAll(): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds a Commercial Earning Commission aggregate by its public identifier.
   *
   * Returns null when no earning commission exists for the supplied public ID.
   */
  findByPublicId(
    publicId: CommercialEarningCommissionPublicId,
  ): Promise<CommercialEarningCommissionAggregate | null>;

  /**
   * Finds the Commercial Earning Commission associated with a Journey
   * Settlement.
   *
   * A Settlement can have at most one Commercial Earning Commission.
   *
   * This corresponds to the persistence invariant represented by the unique
   * settlementPublicId constraint.
   */
  findBySettlementPublicId(
    settlementPublicId: CommercialEarningCommissionSettlementPublicId,
  ): Promise<CommercialEarningCommissionAggregate | null>;

  /**
   * Finds all Commercial Earning Commission aggregates associated with a
   * Journey.
   *
   * A Journey may contain multiple settlements and therefore potentially
   * multiple earning commission records.
   */
  findByJourneyPublicId(
    journeyPublicId: CommercialEarningCommissionJourneyPublicId,
  ): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all Commercial Earning Commission aggregates associated with a
   * Provider.
   *
   * A Provider may have earning commissions across multiple Journeys and
   * Settlements.
   */
  findByProviderPublicId(
    providerPublicId: CommercialEarningCommissionProviderPublicId,
  ): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all Commercial Earning Commission aggregates created using a
   * specific Commercial Commission Rule.
   *
   * The commission rule is referenced by public identity only.
   */
  findByCommissionRulePublicId(
    commissionRulePublicId: CommercialCommissionRulePublicId,
  ): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all Commercial Earning Commission aggregates with the supplied
   * lifecycle status.
   *
   * This is useful for operational workflows such as identifying pending
   * commissions awaiting assessment.
   */
  findByStatus(
    status: CommercialEarningCommissionStatus,
  ): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all pending Commercial Earning Commission aggregates.
   *
   * Pending commissions have not yet been formally assessed.
   */
  findPending(): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all assessed Commercial Earning Commission aggregates.
   *
   * Assessed commissions may subsequently be cancelled according to the
   * aggregate lifecycle rules.
   */
  findAssessed(): Promise<CommercialEarningCommissionAggregate[]>;

  /**
   * Finds all cancelled Commercial Earning Commission aggregates.
   */
  findCancelled(): Promise<CommercialEarningCommissionAggregate[]>;

  // ---------------------------------------------------------------------------
  // Entity Queries
  // ---------------------------------------------------------------------------

  /**
   * Finds a Commercial Earning Commission entity by its public identifier.
   *
   * The aggregate-oriented query should be preferred when aggregate behavior
   * or lifecycle operations are required.
   */
  findEntityByPublicId(
    publicId: CommercialEarningCommissionPublicId,
  ): Promise<CommercialEarningCommissionEntity | null>;

  /**
   * Finds the Commercial Earning Commission entity associated with a
   * Settlement.
   *
   * Settlement public identity is unique within the Commercial Earning
   * Commission persistence model.
   */
  findEntityBySettlementPublicId(
    settlementPublicId: CommercialEarningCommissionSettlementPublicId,
  ): Promise<CommercialEarningCommissionEntity | null>;

  /**
   * Finds all Commercial Earning Commission entities associated with a
   * Journey.
   */
  findEntitiesByJourneyPublicId(
    journeyPublicId: CommercialEarningCommissionJourneyPublicId,
  ): Promise<CommercialEarningCommissionEntity[]>;

  /**
   * Finds all Commercial Earning Commission entities associated with a
   * Provider.
   */
  findEntitiesByProviderPublicId(
    providerPublicId: CommercialEarningCommissionProviderPublicId,
  ): Promise<CommercialEarningCommissionEntity[]>;

  // ---------------------------------------------------------------------------
  // Existence
  // ---------------------------------------------------------------------------

  /**
   * Determines whether a Commercial Earning Commission exists for the supplied
   * public identifier.
   */
  existsByPublicId(
    publicId: CommercialEarningCommissionPublicId,
  ): Promise<boolean>;

  /**
   * Determines whether a Commercial Earning Commission already exists for the
   * supplied Settlement.
   *
   * This supports the invariant that one Settlement can have only one
   * Commercial Earning Commission.
   */
  existsBySettlementPublicId(
    settlementPublicId: CommercialEarningCommissionSettlementPublicId,
  ): Promise<boolean>;

  /**
   * Determines whether at least one Commercial Earning Commission exists for
   * the supplied Journey.
   */
  existsByJourneyPublicId(
    journeyPublicId: CommercialEarningCommissionJourneyPublicId,
  ): Promise<boolean>;

  /**
   * Determines whether at least one Commercial Earning Commission exists for
   * the supplied Provider.
   */
  existsByProviderPublicId(
    providerPublicId: CommercialEarningCommissionProviderPublicId,
  ): Promise<boolean>;
}
