// -----------------------------------------------------------------------------
// Support Case Public ID
// -----------------------------------------------------------------------------
//
// Public identity of a Support Case entity.
//
// This identifier belongs to the Support domain and is therefore modeled
// using the foundation PublicEntityId abstraction.
//
// -----------------------------------------------------------------------------

// -----------------------------------------------------------------------------
// Foundation
// -----------------------------------------------------------------------------

import { PublicEntityId } from '../../../../foundation/kernel/domain/public-entity-id';

// -----------------------------------------------------------------------------
// Public Entity ID
// -----------------------------------------------------------------------------

/**
 * Public identifier of a Support Case.
 *
 * This is the public identity used to reference a Support Case outside
 * the Support domain.
 *
 * The internal database identifier is intentionally not exposed through
 * the domain's public identity.
 *
 * The identifier is generated by the foundation when no value is supplied.
 */
export class SupportCasePublicId extends PublicEntityId {
  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------

  /**
   * Creates a Support Case public ID.
   */
  public constructor(value?: string) {
    super(value, 'SC');
  }
}
